### ISSUE TITLE
Header keywords 'CD1_1', 'CD1_2', 'CD2_1', 'CD2_2' and 'CUNIT1' are general to any observatory header or not?

### ISSUE THREAD

**Issue by VChristiaens** [vortex-exoplanet/VIP#1]
One of the functions I want to add to calib/derotation.py consists in computing the derotation angles list to be applied to each frame to match North up.
This function would be based on the header information.
So far, I have only handled ESO headers. I was wondering if the header keywords 'CD1_1', 'CD1_2', 'CD2_1', 'CD2_2' and 'CUNIT1', which I use in the function, are general to any header of any observatory or if they are specific to ESO?

In the first case, do you think I would better not include the function to VIP, as it would not be general enough?

Thanks.
Valentin

**Comment by oabsil** [comment]
I think they are ESO-specific. Most header entries are 
observatory-specific. Putting observatory-specific routines in VIP is 
probably not a very good idea. Not sure which way to proceed is best. 
Maybe the best way would be to create a new repository for ESO-specific 
(or instrument-specific) recipes, just like we did for NIRC2 pre-processing.

Cheers,
Olivier.


Le 27/08/15 16:47, VChristiaens a écrit :
>
> One of the functions I want to add to calib/derotation.py consists in 
> computing the derotation angles list to be applied to each frame to 
> match North up.
> This function would be based on the header information.
> So far, I have only handled ESO headers. I was wondering if the header 
> keywords 'CD1_1', 'CD1_2', 'CD2_1', 'CD2_2' and 'CUNIT1', which I use 
> in the function, are general to any header of any observatory or if 
> they are specific to ESO?
>
> In the first case, do you think I would better not include the 
> function to VIP, as it would not be general enough?
>
> Thanks.
> Valentin
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vortex-exoplanet/VIP/issues/1>.
>

-- 
--------------------------------------------------
Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46
Email: absil (at) astro.ulg.ac.be
--------------------------------------------------

**Comment by carlgogo** [comment]
For some reason I received more emails from you than the replies I see here. In my opinion (and summarizing what's been said before) the best way to proceed is the following:

 - The derotation.py module stays as it is. It contains functions for rotating 2d or 3d arrays, the angles must be provided.
 - A module like calib/parangles.py will be created and the function depot_angle() could go there. 
 - Such function must have an optional parameter (a dictionary) containing the corresponding 'cd1_1', 'cd1_2', 'cd2_1', 'cd2_2' and 'CUNIT1' keywords in the current header (in case it's not an ESO header).
 - Having the PA in the right format is important (thanks Valentin for finding this bug). In this module parangles.py we should include a function for checking and re-formating the vector of PA if necessary. This is for the case when the user already has already a vector of PA.
 - In the same module I will include the function I had in the old VORTEX repo for calculating  the PA from coordinates and local sidereal time from the header and the latitude of the observatory. I used this function with LBT data.
 - The function for checking the PA vector must be called at the beginning of functions that do some sort of PA thresholding (PCA, ADI, etc).

If you agree I'll close this issue.
