### ISSUE TITLE
Problems importing after name change

### ISSUE THREAD

**Issue by henry-ngo** [vortex-exoplanet/VIP#108]
Congrats on a big change to v0.8! Following the README, I now import vip with

`import vip_hci as vip`

This imports vip as expected. And I can refer to specific functions or modules such as

`vip.fits`, or
`vip.fits.open_fits()`

with no issues. However, when we try to do things like

`import vip_hci as vip
from vip.fits import open_fits`,

we get an error! It says no module named "vip". 

Is there something else we need to do to properly alias "vip_hci" as "vip" for these examples? 

(Backup plan is to just change all lines like "from vip.fits import open_fits" to "vip_hci.fits import open_fits" but just thought I should ask if anyone has a better suggestion)

**Comment by henry-ngo** [comment]
Okay, I found a solution:

`import vip_hci as vip
import sys
sys.modules['vip']=sys.modules['vip_hci']`

Someone told me that Python actually looks through sys.modules to find submodules so we need to set up an alias here too in order to be able to refer to the submodules of vip_hci with the alias vip!

@carlgogo : If you agree that I didn't screw things up even further, could you update the README to include the other two lines?

**Comment by carlgogo** [comment]
Hi @henry-ngo thanks. The change of VIP to VIP_HCI was motivated by the fact that the name VIP was taken at the Python Package Index (Pypi). It's up to you to modify the ``sys.modules`` reference but I would suggest to modify every call: `from vip.submodule import function_x` to `from vip_hci.submodule import function_x`. This fix will be needed only once as there's no reason why we should change the name of the package to something else in the future.

**Comment by henry-ngo** [comment]
Oh okay. Thanks for the clarification! I thought from the README that the intent is to have everyone alias vip_hci as vip. But I'll stick to your suggestion, then.
