### ISSUE TITLE
Bug in the function pca_optimize_snr()?

### ISSUE THREAD

**Issue by VChristiaens** [vortex-exoplanet/VIP#11]
Hi Carlos,

I see the default value of function pca_optimize_snr()'s optional parameter annulus_width is None. However if one changes argument mode to 'annular', the algorithm would arrive to the call of function pca_annulus() without having been assigned a value to annulus_width. In pca_annulus(), this would create an error (as it only accepts float, not None, for annulus_width).

I suggest to change the default value of annulus_width from None to 2; so that the default value for annulus width is set to 2*fwhm (or any preferred value), then to change the description of the parameter correspondingly.

Cheers,
Valentin

**Comment by VChristiaens** [comment]
Actually, 2 might be best for consistency, as it is already the default value for the annuli of function annular_pca() in pca_local.py

**Comment by oabsil** [comment]
I agree with Valentin that 2 would be a good default value. --Oli

Le 21/10/15 14:10, VChristiaens a écrit :
>
> Hi Carlos,
>
> I see the default value of function pca_optimize_snr()'s optional 
> parameter annulus_width is None. However if one changes argument mode 
> to 'annular', the algorithm would arrive to the call of function 
> pca_annulus() without having been assigned a value to annulus_width. 
> In pca_annulus(), this would create an error (as it only accepts 
> float, not None, for annulus_width).
>
> I suggest to change the default value of annulus_width from None to 2; 
> so that the default value for annulus width is set to 2*fwhm (or any 
> preferred value), then to change the description of the parameter 
> correspondingly.
>
> Cheers,
> Valentin
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vortex-exoplanet/VIP/issues/11>.
>

-- 
--------------------------------------------------
Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46
Email: absil (at) astro.ulg.ac.be
--------------------------------------------------

**Comment by carlgogo** [comment]
Hi, 

Indeed it's not the best choice for the default value of *annulus_width* but this is not a bug. I was assuming educated input and as you can see the default value for *mode* is "full". If *mode* is changed to "annular" then the user obviously must give a different value for *annulus_width*. 

The real bad practice here is that I didn't catch the situation when *mode*="annular" and *annulus_width*=None inside the function (with an assert or if not ... raise Error). Throwing an error with an explanation is always better. 

I'll proceed with the quick and dirty "fix": to set the default parameter to 2.  

Cheers,
Carlos
