### ISSUE TITLE
VLT pupil diameter implemented in vip.conf.VLT_SPHERE and vip.conf.VLT_NACO is wrong

### ISSUE THREAD

**Issue by avigan** [vortex-exoplanet/VIP#111]
```python
In [24]: vip.conf.VLT_SPHERE
Out[33]: {'diam': 8.2, 'latitude': -24.627, 'longitude': -70.404, 'plsc': 0.01225}
```
The VLT **mirror diameter** is indeed 8.2 meters, but the physical pupil of the VLT is actually defined by the secondary so that the **pupil diameter** is in fact 8.0 meters.

**Comment by oabsil** [comment]
Hi @avigan 

Based on the information I have, the VLT pupil as seen from Cassegrain focus (case of e.g. VISIR, ERIS) is 8.120m in diameter. Not sure if something stops it down to 8.0m on the Nasmyth platform.

Cheers

**Comment by avigan** [comment]
Hi @oabsil,

Here is an extract of the ESO document entitled ["Requirements for Scientific Instruments on the VLT Unit Telescopes"](https://www.eso.org/sci/facilities/develop/documents/VLT-SPE-ESO-10000-2723_is1.pdf):

![vlt_focus_optical_parameters](https://user-images.githubusercontent.com/29944664/34081511-e5d8fd92-e34d-11e7-8cf1-99e84d811c49.png)

The focus optical parameters are indeed different for the Cassegrain and Nasmyth focii.

Cheers!

**Comment by carlgogo** [comment]
Hello @avigan and @oabsil, is it 8.0m in the end? I'd like to clarify that the values in the instrument dictionaries **are NOT used** anywhere in the code. They are stored just for reference. Even though this values don't affect computations, it would be good to quote the right values.

**Comment by avigan** [comment]
Yes it's 8.0 m for NACO and SPHERE.
