### ISSUE TITLE
No Itertools izip in Python 3.x

### ISSUE THREAD

**Issue by JonasKemmer** [vortex-exoplanet/VIP#116]
Hey, 

I want to use the VIP package with python 3.6. I know the support for python 3.6 will be continuously implemented. At this point, there is still a discrepancy  with ittertools "izip" (which is not available in Python3.6 according to my search).

  File "/home/kemmer/anaconda3/lib/python3.6/site-packages/vip_hci/pca/pca_local.py", line 542, in do_pca_loop
    res = pool.map(EFT, itt.izip(itt.repeat(do_pca_patch),

AttributeError: module 'itertools' has no attribute 'izip'

When will this be fixed? 

Thank's,

Jonas

**Comment by carlgogo** [comment]
Hi @JonasKemmer, thanks for reporting this bug. I have fixed the python3.6 compatibility in the last release. Hopefully this time the transition to py3 is complete. 

Please, subscribe to our mailing list and give us a star. It's a good way to keep track VIP's active users.
