### ISSUE TITLE
Unify the input of coordinates as a tuple (X,Y)

### ISSUE THREAD

**Issue by carlgogo** [vortex-exoplanet/VIP#12]
Hi @owertz @VChristiaens @oabsil 

I noticed the input of pixel coordinates in functions that require it is not consistent, sometimes as separate parameters Y and X and sometimes as a single tuple (X,Y). It makes sense to unify this to have tuples (X,Y) in all the functions that require the input of a px coordinates.

Cheers,
Carlos

**Comment by owertz** [comment]
Hi Carlos,

Thanks for your email. Ok, good.

Cheers,
Olivier

Le 22 oct. 2015 à 13:56, Carlos Gomez <notifications@github.com> a écrit :

> Hi @owertz @VChristiaens @oabsil
> 
> I noticed the input of pixel coordinates in functions that require it is not consistent, sometimes as separate parameters Y and X and sometimes as a single tuple (X,Y). It makes sense to unify this to have tuples (X,Y) in all the functions that require the input of a px coordinates.
> 
> Cheers,
> Carlos
> 
> —
> Reply to this email directly or view it on GitHub.
> 

********************************************************************
Dr. Olivier WERTZ
Postdoctoral Position - VORTEX Project
E-mail : owertz@ulg.ac.be
Email : wertz@astro.ulg.ac.be
Institut d’Astrophysique et de Géophysique, Fac. Sc., AEOS
AGO: http://www.ago.ulg.ac.be
Université de Liège
Allée du 6 Août, 17, B5c,
B-4000 Sart Tilman, Belgique
********************************************************************

**Comment by carlgogo** [comment]
Next step will be to identify all the functions that will need the make-up. Once everyone agrees I'll list the functions "implicated" and make the changes.

Carlos

**Comment by VChristiaens** [comment]
Sure, it makes sense of course.
Cheers,

**Comment by carlgogo** [comment]
Ok, I assume Olivier A. will agree too. I'll include that in my to-do list for next commit.

**Comment by rmjc** [comment]
Hi all, 

Along the same lines, I noticed that line 84 of frame_analysis.py should change from:

fy, fx = fit_2dgaussian(array, y, x, fwhm)

to:

fy, fx = fit_2dgaussian(array, [y, x], fwhm)

**Comment by carlgogo** [comment]
Hi,
It was fixed in a commit I made earlier today. It should be ok now!

Carlos
