### ISSUE TITLE
issue with preproc.cube_correct_nan

### ISSUE THREAD

**Issue by maddalenareggiani** [vortex-exoplanet/VIP#129]
Hi Carlos , 
a new student using VIP here in Liege is having problems with the function
preproc.cube_correct_nan
more precisely, when it calls stats.sigma_clip.
The error is found in lines 74-78 of sigma_clip and it's related to indices not being integer but float.
He is using Python 3.6, could the error be due to that?
Thanks!

**Comment by carlgogo** [comment]
Hi Maddalena, this is indeed a bug that I didn't notice when I made the py2/3 compatiblity. I've corrected it. It should be fine now. Cheers.
