### ISSUE TITLE
PA threshold in annular PCA

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/VIP#14]
Hi @carlgogo 

I'm a bit confused with the behaviour of the PA threshold when applying pca_local.annular_pca on the 2015-10-24 HR8799 ADI data set (files n0040 to n0125). Here is the list of PAs:

array([ 277.89462,  277.62609,  277.34579,  277.07128,  276.73914,
        276.43368,  276.10337,  275.73944,  275.38659,  275.00226,
        274.58319,  274.15879,  273.68044,  273.16059,  272.66642,
        272.09372,  271.46899,  270.81985,  270.15044,  269.39985,
        268.57026,  267.66633,  266.70345,  265.66192,  264.4353 ,
        263.10607,  261.67292,  260.00574,  258.25847,  256.16358,
        253.82578,  251.02348,  247.98707,  244.23552,  239.8129 ,
        234.72543,  228.70085,  221.98772,  213.8008 ,  205.02589,
        125.88666,  124.71132,  123.55023,  122.56172,  121.63624,
        120.79717,  119.99221,  119.30114,  118.67914,  118.0255 ,
        117.45395,  116.95032,  116.45874,  115.97881,  115.53998,
        115.10231,  114.7175 ,  114.36046,  114.00123,  113.6464 ,
        113.34686,  113.03144,  112.75133,  112.47832,  112.20291,
        111.93917,  111.67862,  111.44675,  111.2186 ,  110.99489,
        110.77652,  110.56603,  110.37987,  110.1867 ,  109.99541,
        109.80226,  109.62599])

What I'd like to do is to set a PA threshold so that, for the innermost annuli, the first part of the sequence (277° to 205°) will be "calibrated" by the 2nd part of the sequence (125° to 109°), which basically means that we're doing so kind of RDI between the two parts of the sequence (before and after transit). Here is the kind of result I get:

PA threshold 57.30 is too big, will be set to -75.72
Annulus 1, PA thresh = -75.72, Inn radius = 0.00, Ann center = 8.00 
Done PCA with randsvd for current annulus
Running time:  0:00:00.204388

PA threshold 19.10 is too big, will be set to -75.72
Annulus 2, PA thresh = -75.72, Inn radius = 16.00, Ann center = 24.00 
Done PCA with randsvd for current annulus
Running time:  0:00:00.432867

I don't understand why it complains about the PA threshold being too big, and changes it to -75.72°. Furthermore, the final result of the reduction looks a bit suspicious to me. Could you have a look into this behaviour?

Cheers,
Olivier.

**Comment by carlgogo** [comment]
Hi Olivier,

It might be related to a bug in the definition of the middle point of the PA total range for and ADI sequence (this was spotted recently by Valentin) which affected the PA threshold. I just committed a change that I hope fixes the issue.

Cheers,
Carlos

**Comment by oabsil** [comment]
Hi Carlos,

I'm not sure your fix is enough. The problem is that, when you have an 
angle list of the form [-120, -140, -160, 160, 140, 120], the PA range 
computed by your method is 320°, while the actual range is (-180+120) + 
(180-120) = 120° here because 180° = -180°!

A possible way around is to force all parallactic angles to be positive. 
It's probably not the best way to do, because one would probably prefer 
to keep these values unchanged all through the processing steps. But I'm 
not sure I see another practical way.

In my NIRC2 preprocessing notebook, I added the following line to make 
it work:

angs[np.where(angs < 0)] += 360

Cheers,
Olivier.

Le 25/10/15 04:00, Carlos Gomez a écrit :
>
> Hi Olivier,
>
> It might be related to a bug in the definition of the middle point of 
> the PA total range for and ADI sequence (this was spotted recently by 
> Valentin) which affected the PA threshold. I just committed a change 
> that I hope fixes the issue.
>
> Cheers,
> Carlos
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vortex-exoplanet/VIP/issues/14#issuecomment-150912215>.
>

-- 
--------------------------------------------------
Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46
Email: absil (at) astro.ulg.ac.be
--------------------------------------------------

**Comment by carlgogo** [comment]
Having the PAs all positive is done in vip.calib.parangles.check_PA_vector() which is called at the beginning of the local PCA. So internally the PA vector is converted.
