### ISSUE TITLE
Flux conservation in PCA

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/VIP#15]
Hi @carlgogo ,

Looks like the fluxes are not preserved in the PCA processing. I mean, the flux levels in the final image has nothing to do with the flux levels in the cubes that we feed the PCA with. Keeping the fluxes would be useful to have a quick look at the brightness of the candidate companions, and will be even more important when computing contrast curves.

Cheers!

**Comment by carlgogo** [comment]
Hi @oabsil,

I will answer this in a private email.

Cheers,
Carlos
