### ISSUE TITLE
VIP tutorial

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/VIP#16]
Hi @carlgogo 

There seems to be some issues in the VIP Ipython notebook tutorial. Mike ran into trouble when trying it out, and I could reproduce the issues on my machine. Here are the main ones I've spotted:

vip.phot.detection(fr_adi, fwhm, psf, debug=True, mode='log', snr_thresh=5)
--> there shouldn't be a fwhm argument here

Even with this correction, is crashed after displaying the figure:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-c2dfb7112c26> in <module>()
----> 1 vip.phot.detection(fr_adi, psf, debug=True, mode='log', snr_thresh=5)

/Users/oabsil/Python/vip/vip/phot/detection.pyc in detection(array, psf, bkg_sigma, mode, matched_filter, mask, snr_thresh, plot, debug, full_output, verbose)
    248                                   threshold=bkg_level,
    249                                   min_sigma=sigma-.5, max_sigma=sigma+.5)
--> 250         coords = coords[:,:2]
    251         if coords.shape[0]>0 and verbose:  print_coords(coords)
    252 

IndexError: too many indices for array

vip.phot.snr_student(fr_adi, 63, 62, fwhm, plot=True)
--> does not exist any more

vip.phot.detection(fr_pca, psf, debug=True, mode='log', snr_thresh=5)
--> should be fr_pca1 in input

(I've stopped my exploration here, maybe other bugs remain below)

Could you please update the tutorial?

Cheers,
Olivier.

**Comment by carlgogo** [comment]
Hi @oabsil 

Sure, I'll put that in my to-do list. That version of the tutorial is 5 months old. I'd upload the version of the tutorial I showed in the last yearly meeting (2 months ago) but it's outdated as well (the issue of a daily changing code!!!). 

Cheers,
Carlos

**Comment by carlgogo** [comment]
Done!!! Tutorial updated (30/10/2015)

Carlos
