### ISSUE TITLE
firstguess and run_mcmc_astrometry with RDI

### ISSUE THREAD

**Issue by maddalenareggiani** [vortex-exoplanet/VIP#17]
Hi @carlgogo , 

I don't know if you already looked into adding the possibility to run vip.negfc.simplex_opt.firstguess and vip.negfc.mcmc_opt.run_mcmc_astrometry with RDI.
If not, whenever you have time, could you add that functionality?

Thanks,
Maddalena

**Comment by carlgogo** [comment]
Hi Maddalena,

Yes, this is in the list of top priorities! Give me a couple of days to commit this along with other functionalities I've been working on.

Cheers,
Carlos

**Comment by carlgogo** [comment]
Hi Maddalena,

This has been implemented in the last commit. Try it out!

Carlos

**Comment by maddalenareggiani** [comment]
Thanks, I will!
