### ISSUE TITLE
issue with cube_filter_lowpass in vip.recentering.cube_recenter_via_speckles

### ISSUE THREAD

**Issue by maddalenareggiani** [vortex-exoplanet/VIP#171]
Hi Carlos, 

There is an issue in vip.recentering.cube_recenter_via_speckles.
I think that at lines 1093 and 1096 we need to substitute cube_filter_lowpass with frame_filter_lowpass, otherwise it doesn't work anymore.
   1092 
   1093     cube_sci_lpf = cube_filter_lowpass(cube_sci_lpf[i], 'gauss',
-> 1094                                        fwhm_size=min_spat_freq * fwhm)
   1095     if refStar:
   1096         cube_ref_lpf = cube_filter_lowpass(cube_ref_lpf[i], 'gauss',

Thanks!
Cheers,
Maddalena

**Comment by carlgogo** [comment]
Hi Maddalena. There was an unneeded slicing (the [i]) in lines 1093 and 1096. I took the opportunity to refactor/rewrite the whole function. Please install from the main repo (pip install --upgrade git+https://github.com/vortex-exoplanet/VIP.git) and let me know if it works as expected now. Cheers!
