### ISSUE TITLE
Small bug in pca/utils.py

### ISSUE THREAD

**Issue by VChristiaens** [vortex-exoplanet/VIP#21]
Hola Carlos,

There is a small bug in the scale_cube_for_pca module (that I wrote), throwing me an error that pad lengths should be integers when the function is called. To solve it, the 2 following lines:
        pad_len_y = (new_y - y)/2
        pad_len_x = (new_x - x)/2
have to be changed to:
        pad_len_y = (new_y - y)//2
        pad_len_x = (new_x - x)//2
The reason for that, and I just learned it, is that when one is importing:
from __future__ import division
the result of any division of 2 integers is a float. The result can be forced to be an integer with "//" instead of "/".

Saludos,
Valentin

**Comment by carlgogo** [comment]
Hola Valentin,

Thanks for the fix. Notice that I try to include in almost every module:
from __future__ import division
from __future__ import print_function
That will make easier to implement the compatibility with python 3. Also, the division operator from __future__ (>3.0) is more convenient. 

When I tested the function *scale_cube_for_pca* it worked well and I missed the issue there. It'll be patched in next commit.

Cheers,
Carlos
