### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by r4lv** [vortex-exoplanet/VIP#229]
I found multiple python modules for automatic code formatting

- [google/yapf](https://github.com/google/yapf),
- [hhatto/autopep8](https://github.com/hhatto/autopep8),
- [ambv/black](https://github.com/ambv/black),

and also this [awesome comparison](https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505). While formatting code by hand is certainly prettier, it would be definitely easier to use an automated formatter.

I had a closer look at `black`, which has — besides the line length — no configuration option, so no discussion. I like that 😋 It has plugins for many editors (also jupyter!), and can also be integrated into git as a pre-commit hook.

Also, we could think about the line length — we talked about 100 characters, but when working on my small laptop screen recently, I really appreciated the current 80 chars, so that I can put two windows side-by-side... I vote for keeping the current length.

**Comment by carlgogo** [comment]
As we discussed previously, VIP follows PEP8 very closely, which for instance means that we stick with the 79 chars convection. 

I'm used to formatting everything while I code, but feel free to add a plugin to your editor or IDE (on Pycharm  PEP8 is kind of embedded). Not sure we need to include black as a pre-commit hook but let's keep this open for now in case you have a different opinion.

**Comment by r4lv** [comment]
## mardi, 19.06.2018 11:26:50
### 

I think there are two points to consider: *compliance with a PEP8 style checker* and *consistency*.

Following the recommendations of PEP8 does not automatically make a code consistent. These are valid examples from the PEP8 document:

``` python
# Aligned with opening delimiter.
foo = long_function_name(var_one, var_two,
                         var_three, var_four)

# Hanging indents should add a level.
foo = long_function_name(
    var_one, var_two,
    var_three, var_four)
```

or for `if` statements:

``` python
# No extra indentation.
if (this_is_one_thing and
    that_is_another_thing):
    do_something()

# Add some extra indentation on the conditional continuation line.
if (this_is_one_thing
        and that_is_another_thing):
    do_something()
```

Even if we pass all `pycodestyle` tests, there is still space for personal interpretation. For now, making the VIP code consistent means to look at the existing code and replicate its style, e.g. line continuation, and so on. While I am quite used to your style, it may not be obvious to new contributors.

By using a more strict subset of PEP8, like `black`, that human factor can be removed, as it is 100% defined how code has to look like. It also takes away the *art* and *elegance* of the code, though...

I see two possibilities for continuing:

- Make the linter in PyCharm / `pycodestyle` / `flake8` happy by reformatting the code just so that the tests pass.
- Use an automatic formatter to remove the ambiguities and enforce a consistent style.

What would you prefer?

**Comment by r4lv** [comment]
A few insights:

### PyCharm & pycodestyle

I was digging a bit into the PyCharm "inspections". The "PEP8 coding style violation" inspection uses  `pycodestyle` (formerly `pep8`) internally, but uses its own ignored [codes](https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes) list:

- `W29`
    - `W291` trailing whitespace
    - `W292` no newline at end of file
    - `W293` blank line contains whitespace
- `E501` line too long (82 > 79 characters)<sup>1</sup>

I think that choice is not optimal, e.g. "trailing whitespace" is something extremely annoying — `pycodestyle` by default uses the following ignores:

- `E121` continuation line under-indented for hanging indent
- `E123` closing bracket does not match indentation of opening bracket’s line
- `E126` continuation line over-indented for hanging indent
- `E226` missing whitespace around arithmetic operator
- ` E24`
    - `E241` multiple spaces after ‘,’
    - `E242` tab after ‘,’
- `E704` multiple statements on one line (def)
- `W503` line break before binary operator
- `W504` line break after binary operator

The inspections settings for PyCharm can be stored per-project in `<project>/.idea/inspectionProfiles/`.

### flake8 & co

`flake8` is built around `pycodestyle`, but also adds [non-PEP8 checks](http://flake8.pycqa.org/en/latest/user/error-codes.html#error-violation-codes), e.g. unused imports and so. The `pycodestyle` project itself uses `flake8` for its style checks. The configuration is stored in the project directory in the `[flake8]` section of `setup.cfg` or `tox.ini`, or the `.flake8` file.

Editor integrations for Sublime Text ([SublimeLinter-flake8](https://github.com/SublimeLinter/SublimeLinter-flake8)), Atom ([linter-flake8](https://atom.io/packages/linter-flake8)), VSCode ([integrated](https://code.visualstudio.com/docs/python/linting#_flake8)) and others read directly from the `flake8` configuration files. There is currently no integration of `flake8` in PyCharm, but it's in the [issue tracker](https://youtrack.jetbrains.com/issue/PY-8192), an the [roadmap of the coalas project](https://projects.coala.io/#/projects?project=plugin_for_jetbrains_ides&lang=en).

`flake8` can also be automatically run for Pull Requests with [stickler CI](https://stickler-ci.com/docs#python), which is free for open source projects (like Travis CI).

### solution? / summary

- [ ] We should define a list of ignored checks for VIP.
- [ ] The configuration should be stored inside a `.flake8` file, to make common editors/IDEs happy.
- [ ] PyCharm needs a specific configuration inside the `.idea/`directory
- [ ] flake8 can be automatically run on Pull Requests by [stickler CI](https://stickler-ci.com/docs#python), which would require another configuration file.
 
 
---

<sup>1</sup> PyCharm has its own "Line is longer than allowed by code style" inspection in the "General" category, which is off by default.

**Comment by r4lv** [comment]
**Update:** there is now a [pylint plugin](https://plugins.jetbrains.com/plugin/11084-pylint) for PyCharm. Pylint is an alternative to Pyflakes/flake8. Pylint can also be configured using a configuration file.

One would need to check for correspondence between [pylint error codes](http://pylint-messages.wikidot.com/all-codes) and the [flake8 rules](https://lintlyci.github.io/Flake8Rules/), and maintain two configuration files, which produce similar output in the respective tool.

I'll check if that is a good way to go.

**Comment by r4lv** [comment]
see https://github.com/vortex-exoplanet/VIP/pull/315

**Comment by VChristiaens** [comment]
Pull request https://github.com/vortex-exoplanet/VIP/pull/315 has now been accepted, hence closing this issue.
