### ISSUE TITLE
Small bugs in phot/fakecomp.py

### ISSUE THREAD

**Issue by VChristiaens** [vortex-exoplanet/VIP#23]
Hola @carlgogo ,

As it is, there are 2 small bugs in function psf_norm (phot/fakecomp.py):
1) the first is related to variable "size": if it takes the value "None", an error would be raised.
You could add the following line at l.153 to avoid the bug:
else: psfs = array.copy()
(this would also require to import copy)
2) The description of variable "array" states that it should consist of the relative path of the psf fits image, while it is the psf array itself that is required.

Saludos,
Valentin

**Comment by carlgogo** [comment]
Hola @VChristiaens,

Indeed, that's a bug, thanks for pointing that out. I've used the line you suggested. Notice that you can call the method copy() on any numpy array without importing copy.

Saludos,
Carlos
