### ISSUE TITLE
All `Warning`s are suppressed

### ISSUE THREAD

**Issue by r4lv** [vortex-exoplanet/VIP#233]
The `pca` submodule runs

``` python
import warnings
warnings.filterwarnings("ignore", category=Warning)
```

which results in a suppression of every warning after VIP is imported. I think this is undesired, as we may want to raise e.g. `DeprecationWarning`s in the future, or don't want to touch the warnings of other packages unrelated to VIP.

I suggest to remove those `filterwarnings` completely, test the code thoroughly, and then add a more precise filter if we need one, e.g. with

``` python
with warnings.catch_warnings():
    # ...
```
or by using the `module` and `lineno` parameters of `filterwarnings`.

**Comment by carlgogo** [comment]
This is debris from an old version of VIP and prevented some excessive output while calling scikit-learn. With current versions of VIP and Sklearn this lines are not needed anymore. I've removed the lines and will send the changes together in a PR I'm working on.
