### ISSUE TITLE
Unexpected error in vip.pca

### ISSUE THREAD

**Issue by henry-ngo** [vortex-exoplanet/VIP#24]
The PCA reduction works for most of our data, but fails on one with an error message that I do not understand: ValueError: work array size computation for internal gesdd failed: -10. The error message seems to be generated by a scipy package though. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-28a8e8b4136b> in <module>()
     39 
     40 # Full Frame ADI PCA
---> 41 image = pca(cube_hpf_0227, angs_0227, ncomp=5, svd_mode='randsvd', full_output=False, mask_center_px=0)
     42 display_array_ds9(image)
     43 

/Users/henryngo/SourceTreeRepos/VIP/vip/pca/pca_fullfr.pyc in pca(cube, angle_list, cube_ref, scale_list, ncomp, ncomp2, svd_mode, scaling, mask_center_px, full_output, verbose, debug)
    316         residuals_result = subtract_projection(cube, None, ncomp, scaling, 
    317                                                mask_center_px, debug, svd_mode,
--> 318                                                verbose, full_output)
    319         if full_output:
    320             residuals_cube = residuals_result[0]

/Users/henryngo/SourceTreeRepos/VIP/vip/pca/pca_fullfr.pyc in subtract_projection(cube, cube_ref, ncomp, scaling, mask_center_px, debug, svd_mode, verbose, full_output)
    145             ref_lib = matrix
    146 
--> 147         V = svd_wrapper(ref_lib, svd_mode, ncomp, debug, verbose)
    148 
    149         if verbose: timing(start_time)

/Users/henryngo/SourceTreeRepos/VIP/vip/pca/utils.pyc in svd_wrapper(matrix, mode, ncomp, debug, verbose, usv)
    291     elif mode=='randsvd':
    292         U, S, V = randomized_svd(matrix, n_components=ncomp, n_iter=2, 
--> 293                                  transpose='auto', random_state=None)
    294         if debug: reconstruction(ncomp, U, S, V, 1)
    295         if verbose: print('Done SVD/PCA with randomized SVD')

/Users/henryngo/anaconda/lib/python2.7/site-packages/sklearn/utils/extmath.pyc in randomized_svd(M, n_components, n_oversamples, n_iter, transpose, flip_sign, random_state)
    301 
    302     # compute the SVD on the thin matrix: (k + p) wide
--> 303     Uhat, s, V = linalg.svd(B, full_matrices=False)
    304     del B
    305     U = np.dot(Q, Uhat)

/Users/henryngo/anaconda/lib/python2.7/site-packages/scipy/linalg/decomp_svd.pyc in svd(a, full_matrices, compute_uv, overwrite_a, check_finite)
     97     lwork, info = gesdd_lwork(a1.shape[0], a1.shape[1], compute_uv=compute_uv, full_matrices=full_matrices)
     98     if info != 0:
---> 99         raise ValueError('work array size computation for internal gesdd failed: %d' % info)
    100     lwork = int(lwork.real)
    101 

ValueError: work array size computation for internal gesdd failed: -10

**Comment by carlgogo** [comment]
It's indeed an error related to Scipy, more specifically when it calls the LAPACK gessd procedure for computing the SVD. I've never seen this error myself, so it's hard to tell what went wrong. 

Please pull the latest VIP version and try calling the vip.pca.pca() with the sad_mode='lapack' instead of 'randsvd' to see if there is any difference. Also, what's the size of cube_hpf_0227?

Carlos

**Comment by henry-ngo** [comment]
Changing the sad_mode from randsvd to lapack did not make a difference. However, I realise now that cube_hpf_0227 is empty (size=0)!

Going back through the arrays, it looks like the problem is that NIRC2_preprocessing.cube_registration() is returning an empty array.

So, then I thought the problem might be with our initial guess for the vortex center (and the "dust" center). It turns out that the vortex initial guess was a few pixels off and changing this resolved the problem. So, vip.pca.pca() runs as expected (with the original sad_mode='randsvd" setting)

Although this does leave me a little concerned that our results are depending a lot on the initial guess. I'll talk to Dimitri and Olivier further about this. 

Thanks!!

**Comment by oabsil** [comment]
Hi Henry,

Olivier Wertz should be in copy of this bug report and, as the developer 
of the NIRC2_preprocessing package, will probably have a look into this 
issue in the coming days. Could you open a bug report in 
NIRC2_preprocessing and give us more details (e.g., by how many pixels 
were you off in your estimation of the vortex center?).

Cheers,
Olivier.

Le 14/12/15 18:11, Henry Ngo a écrit :
>
> Changing the sad_mode from randsvd to lapack did not make a 
> difference. However, I realise now that cube_hpf_0227 is empty (size=0)!
>
> Going back through the arrays, it looks like the problem is that 
> NIRC2_preprocessing.cube_registration() is returning an empty array.
>
> So, then I thought the problem might be with our initial guess for the 
> vortex center (and the "dust" center). It turns out that the vortex 
> initial guess was a few pixels off and changing this resolved the 
> problem. So, vip.pca.pca() runs as expected (with the original 
> sad_mode='randsvd" setting)
>
> Although this does leave me a little concerned that our results are 
> depending a lot on the initial guess. I'll talk to Dimitri and Olivier 
> further about this.
>
> Thanks!!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vortex-exoplanet/VIP/issues/24#issuecomment-164497845>.
>

-- 
--------------------------------------------------
Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46
Email: absil (at) astro.ulg.ac.be
--------------------------------------------------

**Comment by owertz** [comment]
Holà Oli,

Je vais attendre d’avoir plus d’info de sa part, via le bug report,
avant d’investiguer. 

Bonne soirée,
Oli


Le 14 déc. 2015 à 18:27, Olivier Absil <notifications@github.com> a écrit :

> Hi Henry,
> 
> Olivier Wertz should be in copy of this bug report and, as the developer 
> of the NIRC2_preprocessing package, will probably have a look into this 
> issue in the coming days. Could you open a bug report in 
> NIRC2_preprocessing and give us more details (e.g., by how many pixels 
> were you off in your estimation of the vortex center?).
> 
> Cheers,
> Olivier.
> 
> Le 14/12/15 18:11, Henry Ngo a écrit :
> >
> > Changing the sad_mode from randsvd to lapack did not make a 
> > difference. However, I realise now that cube_hpf_0227 is empty (size=0)!
> >
> > Going back through the arrays, it looks like the problem is that 
> > NIRC2_preprocessing.cube_registration() is returning an empty array.
> >
> > So, then I thought the problem might be with our initial guess for the 
> > vortex center (and the "dust" center). It turns out that the vortex 
> > initial guess was a few pixels off and changing this resolved the 
> > problem. So, vip.pca.pca() runs as expected (with the original 
> > sad_mode='randsvd" setting)
> >
> > Although this does leave me a little concerned that our results are 
> > depending a lot on the initial guess. I'll talk to Dimitri and Olivier 
> > further about this.
> >
> > Thanks!!
> >
> > —
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/vortex-exoplanet/VIP/issues/24#issuecomment-164497845>.
> >
> 
> -- 
> --------------------------------------------------
> Dr. Olivier ABSIL
> F.R.S.-FNRS Research Associate
> Dept. of Astrophysics, Geophysics and Oceanography
> Université de Liège (ULg), bât. B5c
> 17 allée du Six Août Tel: +32-(0)4-366.97.24
> B-4000 Sart-Tilman Fax: +32-(0)4-366.97.46
> Email: absil (at) astro.ulg.ac.be
> --------------------------------------------------
> 
> —
> Reply to this email directly or view it on GitHub.
> 

********************************************************************
Dr. Olivier WERTZ
Postdoctoral Position - VORTEX Project
E-mail : owertz@ulg.ac.be
Email : wertz@astro.ulg.ac.be
Institut d’Astrophysique et de Géophysique, Fac. Sc., AEOS
AGO: http://www.ago.ulg.ac.be
Université de Liège
Allée du 6 Août, 17, B5c,
B-4000 Sart Tilman, Belgique
********************************************************************

**Comment by henry-ngo** [comment]
Bonjour Olivier,

J'écris un bug report pour ce problème:
https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/4

Merci!
Henry

(P.S. Je suis désolé---je ne parle pas bien français! Il ya 10 ans depuis
mon cours de français.)

**Comment by owertz** [comment]
Hi Henry,

Thanks for your email as well as for the extra details. 
I’ll take a look to this issue soon. 

> (P.S. Je suis désolé---je ne parle pas bien français! Il ya 10 ans depuis
> mon cours de français.)
It’s perfect. Sorry for my previous email. I thought that it was only sent to Olivier,
that’s why I've written it in French ;-) 

Cheers,
Olivier

Le 14 déc. 2015 à 19:20, Henry Ngo <notifications@github.com> a écrit :

> Bonjour Olivier,
> 
> J'écris un bug report pour ce problème:
> https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/4
> 
> Merci!
> Henry
> 
> (P.S. Je suis désolé---je ne parle pas bien français! Il ya 10 ans depuis
> mon cours de français.)
> 
> On Mon, Dec 14, 2015 at 9:41 AM, owertz <notifications@github.com> wrote:
> 
> > Holà Oli,
> >
> > Je vais attendre d’avoir plus d’info de sa part, via le bug report,
> > avant d’investiguer.
> >
> > Bonne soirée,
> > Oli
> >
> >
> >
> > Le 14 déc. 2015 à 18:27, Olivier Absil <notifications@github.com> a écrit
> > :
> >
> > > Hi Henry,
> > >
> > > Olivier Wertz should be in copy of this bug report and, as the developer
> > > of the NIRC2_preprocessing package, will probably have a look into this
> > > issue in the coming days. Could you open a bug report in
> > > NIRC2_preprocessing and give us more details (e.g., by how many pixels
> > > were you off in your estimation of the vortex center?).
> > >
> > > Cheers,
> > > Olivier.
> > >
> > > Le 14/12/15 18:11, Henry Ngo a écrit :
> > > >
> > > > Changing the sad_mode from randsvd to lapack did not make a
> > > > difference. However, I realise now that cube_hpf_0227 is empty
> > (size=0)!
> > > >
> > > > Going back through the arrays, it looks like the problem is that
> > > > NIRC2_preprocessing.cube_registration() is returning an empty array.
> > > >
> > > > So, then I thought the problem might be with our initial guess for the
> > > > vortex center (and the "dust" center). It turns out that the vortex
> > > > initial guess was a few pixels off and changing this resolved the
> > > > problem. So, vip.pca.pca() runs as expected (with the original
> > > > sad_mode='randsvd" setting)
> > > >
> > > > Although this does leave me a little concerned that our results are
> > > > depending a lot on the initial guess. I'll talk to Dimitri and Olivier
> > > > further about this.
> > > >
> > > > Thanks!!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/vortex-exoplanet/VIP/issues/24#issuecomment-164497845>.
> > > >
> > >
> > > --
> > > --------------------------------------------------
> > > Dr. Olivier ABSIL
> > > F.R.S.-FNRS Research Associate
> > > Dept. of Astrophysics, Geophysics and Oceanography
> > > Université de Liège (ULg), bât. B5c
> > > 17 allée du Six Août Tel: +32-(0)4-366.97.24
> > > B-4000 Sart-Tilman Fax: +32-(0)4-366.97.46
> > > Email: absil (at) astro.ulg.ac.be
> > > --------------------------------------------------
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > ********************************************************************
> > Dr. Olivier WERTZ
> > Postdoctoral Position - VORTEX Project
> > E-mail : owertz@ulg.ac.be
> > Email : wertz@astro.ulg.ac.be
> > Institut d’Astrophysique et de Géophysique, Fac. Sc., AEOS
> > AGO: http://www.ago.ulg.ac.be
> > Université de Liège
> > Allée du 6 Août, 17, B5c,
> > B-4000 Sart Tilman, Belgique
> > ********************************************************************
> >
> >
> >
> >
> >
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vortex-exoplanet/VIP/issues/24#issuecomment-164505711>
> > .
> >
> —
> Reply to this email directly or view it on GitHub.
> 

********************************************************************
Dr. Olivier WERTZ
Postdoctoral Position - VORTEX Project
E-mail : owertz@ulg.ac.be
Email : wertz@astro.ulg.ac.be
Institut d’Astrophysique et de Géophysique, Fac. Sc., AEOS
AGO: http://www.ago.ulg.ac.be
Université de Liège
Allée du 6 Août, 17, B5c,
B-4000 Sart Tilman, Belgique
********************************************************************

**Comment by henry-ngo** [comment]
It's no problem that your email was in French; I think I was able to
understand it. My apology was for any potential bad French mistakes I made
(and may make in the future!). I'm planning to take more French classes in
2016 :)
