### ISSUE TITLE
Improve doc with sphinx-gallery

### ISSUE THREAD

**Issue by r4lv** [vortex-exoplanet/VIP#250]
We already talked about it, but it would be good to keep track with an issue.

[Sphinx Gallery](https://sphinx-gallery.readthedocs.io/en/latest/) uses its own markup to define "input" and "output" cells. That's one more thing to "learn", and one more thing to maintain.

As an alternative, I've found [nbsphinx](http://nbsphinx.readthedocs.io/en/0.3.3/), which allows for jupyter notebooks to be included directly into the documentation. Maybe that would simplify the creation and maintenance of the code examples.

I'll try both and keep this issue up to date.

**Comment by carlgogo** [comment]
Sounds good! Please update this thread when you have some news.

**Comment by VChristiaens** [comment]
Documentation was revamped to include tutorials, using [nbsphinx](http://nbsphinx.readthedocs.io/en/0.3.3/). Closing this issue accordingly.
