### ISSUE TITLE
Suggestion for vip.calib.cube_derotate()

### ISSUE THREAD

**Issue by owertz** [vortex-exoplanet/VIP#27]
Hi @carlgogo,

I hope you're doing well. 

For the function **vip.calib.cube_derotate()**, @oabsil and I would suggest to add a shape matching check between the number of frames in the input *array* and the number of parallactic angles (PA) given in the *angle_list*. Since the loop is performed on the number *N* of frames, the function consistently raises an error when the number of PA is smaller than *N*. However, the function runs well without raising any error or warning when the number of PA is greater than *N*. It might be useful to prevent the case when bad frames are removed from the cube while forgetting to do the same for the corresponding PA in the PA vector. I would suggest to insert the following code after the line 91 in vip.calib.derotation.py:
```Python
if not array.shape[0] == angle_list.shape[0]:
    raise TypeError('Pythonic error message of your choice')
```
which should do the trick. 

Cheers,
Olivier

**Comment by carlgogo** [comment]
Hi @owertz,

This is indeed a good idea, thanks. I should include these tests more consistently in VIP. There are functions missing input sanity checks and this was a good example.

Cheers,
Carlos
