### ISSUE TITLE
var.shapes.mask_circle() ignores `fillwith`

### ISSUE THREAD

**Issue by r4lv** [vortex-exoplanet/VIP#279]
The `var/shapes.py::mask_circle()` function has two modes of operation, `mode="in"` and `"out"`. When using `in`, the inner region is filled with the argument `fillwith` (which defaults to `0`). However, using `mode="out"`, that argument is not used, and the outer region is filled with `nan`:

![capture d ecran 2018-08-07 a 16 58 47](https://user-images.githubusercontent.com/37106979/43783941-3a9169d8-9a63-11e8-8958-97be634e0f4a.png)

1. Is this the intended behaviour? Shouldn't `out` also take into account `fillwith`?
2. Maybe the default value (for `out` only?) could be changed to `nan`?

**Comment by carlgogo** [comment]
This function is used mostly/only for masking out (filling with zeros) the center of coronagraphic images. I'm not against changing the behaviour: making the ``mode="out"`` aware of the ``fillwith`` value. It could be just easier to mention that ``nan`` are used when ``mode="out"``.

**Comment by carlgogo** [comment]
Solved in #281
