### ISSUE TITLE
Annular PCA in RDI mode

### ISSUE THREAD

**Issue by rmjc** [vortex-exoplanet/VIP#29]
Dear all, 

This is more of a suggestion than an issue, but it would be very useful to be able to run annular PCA in RDI mode (currently, only full frame PCA has that option). 

Thanks!

Rebecca

**Comment by carlgogo** [comment]
Hi Rebecca,

This is a feature I'm currently working on. It needs more testing before it can be included in the main branch of VIP. I'll comment on this thread to let you know it's available. 

Cheers,
Carlos

**Comment by carlgogo** [comment]
Hi Rebecca,
Check out latest version of VIP (0.4). An annular version of RDI PCA was included. 
Carlos
