### ISSUE TITLE
bug in preproc/rescaling.py::_find_indices_sdi()

### ISSUE THREAD

**Issue by r4lv** [vortex-exoplanet/VIP#299]
Let's consider the following case:

``` python
wl = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # 10 wavelengths / scaling factors
dist = 15  # star-center separation
index_ref = 5  # wavelength "6" is the reference
fwhm = 4
delta_sep = 1  # in FWHM
```

`_find_indices_sdi()` should then return the indices of `wl` where the separation is `> 1 FWHM`. Setting `debug=True` results in (annotated for readability):

``` python
>>> indices = vip.preproc.rescaling._find_indices_sdi(wl, dist, index_ref, fwhm, delta_sep)
i=0, sep=3.95833, sep_pxs=15.83333
i=1, sep=3.16667, sep_pxs=12.66667
i=2, sep=2.37500, sep_pxs=9.50000
i=3, sep=1.58333, sep_pxs=6.33333
i=4, sep=0.79167, sep_pxs=3.16667
→ Index 1: index_w2=4
i=9, sep=1.83333, sep_pxs=7.33333
i=8, sep=1.37500, sep_pxs=5.50000
i=7, sep=0.91667, sep_pxs=3.66667
→ Index 2: index_w3=7
```

Apparently `index_w2` and `index_w3` are the first indices to be **excluded**, as the separation is `<= 1 FWHM`. The output is however:

``` python
>>> indices
array([0, 1, 2, 3, 7, 8, 9])
```

So `index_w2=4` was correctly excluded, but `index_w3=7` was **included**.

Is this the desired behaviour? Shouldn't it rather return `array([0, 1, 2, 3,      8, 9])`?

**Comment by r4lv** [comment]
I would change it to `index_w3 + 1` in line 539:
https://github.com/vortex-exoplanet/VIP/blob/1e8c7a91c6f257710027694aef6fb5c3349006e6/vip_hci/preproc/rescaling.py#L538-L540

**Comment by r4lv** [comment]
Actually, I discovered more results which seem off. I re-implemented the function using simple array operations:

1. calculate the separation for every index, starting from the left (using the same formula as in the old version)
2. calculate separation from the right
3. select every index where the separation (from left, or from right), is `>= delta_sep`.

Let's compare the old version with my new one.

#### 1. reference index included

``` text
=== dist=10, index_ref=0 ===
all_seps_left:  +0.000  -3.500  -7.000  -10.500  -14.000  -17.500  -21.000  -24.500  -28.000  -31.500
all_seps_right: +0.000  +1.500  +3.000  +4.500  +6.000  +7.500  +9.000  +10.500  +12.000  +13.500
new indices: [1 2 3 4 5 6 7 8 9]
old indices: [0 1 2 3 4 5 6 7 8 9]
```

The old version includes `0` in the indices, which was the requested `index_ref`. That shouldn't be included, as the separation would be zero?

#### 2. indices with separation=1.0 excluded

``` text
=== dist=10, index_ref=5
all_seps_left:  +2.917  +2.333  +1.750  +1.167  +0.583  +0.000  -0.583  -1.167  -1.750  -2.333
all_seps_right: -1.250  -1.000  -0.750  -0.500  -0.250  +0.000  +0.250  +0.500  +0.750  +1.000
new indices: [0 1 2 3 9]
old indices: [0 1 2 3]
```

The old version skipped the indices where the separation from "outside" is exactly `1.0`.


Do you agree with my discoveries?

**Comment by carlgogo** [comment]
Hi @r4lv, this function was created not long ago and definitively needs improvements (there is a TODO tag in there). I encourage you to conduct thorough tests and see how it could be replaced/fixed. For instance, I'm not totally convinced that the lines 500-501 (finding the radial distance between a given frame/WL and a reference one) are totally correct.

The best way to share this would be a gist notebook, instead of copy pasting here. Please use synthetic WL vectors as well as the real ones (SPHERE data) for your tests.

**Comment by r4lv** [comment]
This was fixed by https://github.com/vortex-exoplanet/VIP/pull/308
