### ISSUE TITLE
Fourier shift implementation

### ISSUE THREAD

**Issue by carlgogo** [vortex-exoplanet/VIP#30]
This would be a nice addition to VIP, having the option to perform geometric transformation on images (shift and rotation) with FFTs instead of conventional interpolation (Hagelberg et al. 2015). The challenge is to implement this efficiently, without impacting too much the computational cost.

**Comment by oabsil** [comment]
Hi @carlgogo,

I wouldn't put too much priority on that for now. I think there are more 
urgent and important topics to address first.

Cheers,
Olivier.


Le 20/01/16 11:04, Carlos Gomez a écrit :
>
> This would be a nice addition to VIP, having the option to perform 
> geometric transformation on images (shift and rotation) with FFTs 
> instead of conventional interpolation (Hagelberg et al. 2015). The 
> challenge is to implement this efficiently, without impacting too much 
> the computational cost.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vortex-exoplanet/VIP/issues/30>.
>

-- 
--------------------------------------------------
Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46
Email: absil (at) astro.ulg.ac.be
--------------------------------------------------

**Comment by carlgogo** [comment]
For the record this was partially addressed, at least for the fourier shifting, in VIP 0.5.3.

**Comment by avigan** [comment]
If you want I have implemented a small set of image transformation routines in the following module: https://github.com/avigan/Python-utils/blob/master/vigan/utils/imutils.py

It includes FFT routines to shift, rotate and scale images.

**Comment by carlgogo** [comment]
@avigan Thank you for pointing out to your implementations of the FFT based geometric transformations. Would you like to contribute them to ``VIP``? Otherwise, I could take the ``_***_fft`` functions and adapt them to ``VIP`` myself. 

Of course the optimal solution would be to have a single version of such functions (avoid code redundancy) and to import them from the corresponding package.

**Comment by avigan** [comment]
@carlgogo I would be happy to contribute them but I don't have much time to do it properly at the moment. If there is no rush I can try to do it over the next month.

I agree that a single version maintained somewhere would be better, but I am afraid that there will always be many versions of these for of utility functions floating around...

**Comment by r4lv** [comment]
The `andromeda` submodule module use fourier-based subpixel-shifting to create the PSF library:
https://github.com/vortex-exoplanet/VIP/blob/4912a20a7623095ab950403e3de223cd23c704a6/vip_hci/andromeda/shift.py#L63-L66

Maybe this part could be generalized and factored out?

**Comment by VChristiaens** [comment]
As of VIP v1.0.1, all shift, scaling and rotation operations can now be made through FFT-based algorithms.
Activating the FFT-based methods only requires setting `imlib = 'ndimage-fourier'`, `imlib = 'vip-fft'` and `imlib = 'vip-fft'`  for image shift, scaling and rotation routines, respectively.
New tests have been added to the jupyter notebook tutorial (at vortex-exoplanet/VIP_extras) to compare the performance of the different interpolation-based and FFT-based methods. The latter are, as expected, more accurate and preserve much better the flux, but significantly slower in the case of rotations.
