### ISSUE TITLE
Contrast curve and forward modeling with RDI

### ISSUE THREAD

**Issue by dmawet** [vortex-exoplanet/VIP#31]
Hi Carlos et al.,

It seem like there is not support for RDI in the current contrast curve computation script. Do you plan to do that? It seems like an easy update. Looking at the code, we need to add both an entry for the reference cube, and a condition for RDI in the line 285 to 307 & 363 to 382 sections, right?

I may attempt to do that mysefl if I find the time.

Best,

Dimitri

**Comment by carlgogo** [comment]
Hi Dimitri,

Indeed the support for RDI in the contrast curve function requires a small change, very straightforward to implement. I hesitated to include it, before fully understanding the effect of PCA when a reference library is used. According to my tests it's not as simple as plugging in a second cube to learn some principal components onto which to project the science frames. In most cases some flux scaling or variable scaling must be done, but I haven't reached a conclusion about this. 

I'll proceed to implement the change in the contrast curve using the full-frame PCA for RDI as it is. It must be used with care. 

Cheers,
Carlos

**Comment by carlgogo** [comment]
Check-out latest commit (major update, VIP 0.4). The *contrast_curve* function now works for every PCA function in VIP: 'pca-adi-fullfr', 'pca-rdi-fullfr', 'pca-adi-annular', 'pca-rdi-annular'.

Carlos
