### ISSUE TITLE
The Jupyter notebook tutorial page gives "400 : Bad Request"

### ISSUE THREAD

**Issue by rmjc** [vortex-exoplanet/VIP#32]
Hello, 

Just letting you know that the tutorial notebook (http://nbviewer.jupyter.org/github/vortex-exoplanet/VIP/blob/master/tutorial/Tutorial_VIP.ipynb) gives the error "400 : Bad Request" right now. 

Thanks!

Becky

**Comment by rmjc** [comment]
Looks like it's back up!

**Comment by carlgogo** [comment]
Hi Rebecca, this sometimes happens with the NBVIEWER service and there's not much we can do about it. If it happens again, please visualize the jupyter tutorial on Github, just browse to the tutorial folder and click on Tutorial_VIP.ipynb. 

Carlos
