### ISSUE TITLE
BUG: ADI+RDI PCA wants to return values which do not exist

### ISSUE THREAD

**Issue by r4lv** [vortex-exoplanet/VIP#337]
The `pca/pca_fullfr.py::_adi_rdi_pca()` function has one single `return` statement, which will obviously fail if `full_output=False`, as some return values are only calculated when `full_output=True`.

It should be checked if `full_output` is actually needed/required, and if the logic can be cleaned up a bit.

**Comment by r4lv** [comment]
I did not attack this yet, as I have no means of testing the ADI+RDI case...

If you have an idea for this, let me know.

**Comment by carlgogo** [comment]
@r4lv I have now a dataset you could use for testing ADI+RDI. To be shared in the coming days

**Comment by carlgogo** [comment]
This has been fixed.
