### ISSUE TITLE
BUG: compute_binary_map uses wrong index for segments

### ISSUE THREAD

**Issue by r4lv** [vortex-exoplanet/VIP#341]
In #320, you changed the indexing of `segments.areas[iblob]` to `segments.areas[iblob-1]`. Why is that?

[`photutils.detect_sources`](https://photutils.readthedocs.io/en/stable/api/photutils.segmentation.detect_sources.html) returns a [`SegmentationImage`](https://photutils.readthedocs.io/en/stable/api/photutils.segmentation.SegmentationImage.html) object. There, *source* regions are labeled with *positive* integer values (with 0 being the background) . However, `areas` and `labels` only contain those *non-zero* labels, so the indices of `segments.labels` and `segments.areas` should be the same.

**Comment by carlgogo** [comment]
With ``photutils`` 0.4.1 (version pinned in the requirements), ``compute_binary_map`` was giving an error similar to a "index out of range" one. I don't remember the details but the ``iblob-1`` was the only way to obtain the desire results. You should clarify this.

**Comment by r4lv** [comment]
Right 👍

I didn't see that mentioned in the photutils changelog, but I found it in the code. Here is the change, for future reference:

https://github.com/astropy/photutils/compare/v0.4...v0.4.1#diff-00e7811220b26f668b507adf3d53f191R161
