### ISSUE TITLE
resampling: round vs int

### ISSUE THREAD

**Issue by ChrisDelaX** [vortex-exoplanet/VIP#346]
Hey Carlos! I started using VIP, works great. 
I am relaying this UserWarning that you might find interesting.
Cheers

```python
""" VIP: resample psf_ON and psf_OFF to match the instrument pixelscale """
psf_ON = vip_hci.preproc.cube_px_resampling(psf_ON, psc_simu/psc_inst)

## -- End pasted text --
/Applications/anaconda3/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:583: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
Cube successfully rescaled
New shape: (15, 488, 488)

In [2]: vip_hci.__version__
Out[2]: '0.9.7'
```

**Comment by r4lv** [comment]
You can safely ignore this warning, as VIP (as far as I know) never used scipy < 0.17 (version 0.13 is from 2013…).

@carlgogo We could silence that specific warning by wrapping the call to `zoom` with something like

``` python
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    zoom(...)
```

would you like me to add a PR?

**Comment by carlgogo** [comment]
@ChrisDelaX which function/class in VIP were you using when you got this error? @r4lv do you mean happens because the user has scipy < 0.17 installed?

**Comment by r4lv** [comment]
No, that warning is shown by scipy in every version > 0.13, when `zoom` produces a different result than what it used to **before** 0.13.

That warning is completely useless, as VIP is made for the *new* (>0.13) scipy.
