### ISSUE TITLE
DS9 connection is broken with the latest DS9 and the master of pyds9

### ISSUE THREAD

**Issue by carlgogo** [vortex-exoplanet/VIP#349]
After updating SaoImageDS9, the pyds9 connection stopped working (``TypeError: expected str, bytes or os.PathLike object, not NoneType``). This is most likely an issue to be opened on the pyds9 repository (to be confirmed).

**Comment by r4lv** [comment]
`brew` installs version 7.6 under a different name (`SAOImageDS9.app` instead of `SAOImage DS9.app`, note the space), so pyds9 cannot find the app any more. Renaming the `.app` to include a space before `DS9` fixes the problem for me.

**Comment by carlgogo** [comment]
I thought this may be the cause, but I keep getting the same error even after renaming the app. Btw, the binary (from the official website) installs a ``SAOImageDS9.app`` file, so I'm not sure why ``pyds9`` would be looking for ``SAOImage DS9``.

**Comment by r4lv** [comment]
The old version 7.5, which I used before, had the space in the filename, they seem to have changed it.
Did you try to `File > XPA > Connect`?

**Comment by r4lv** [comment]
BTW, did you silence the `warnings` somehow? When having the app **without** the space, I get the following warning on `import vip_hci as vip`:

```
/.../python3.6/site-packages/pyds9/pyds9.py:103: UserWarning: Can't locate the X11 DS9
executable in your PATH or the Aqua SAOImage DS9 app in /Applications, $HOME or
$HOME/Applications. Please configure your PATH or make SAOImage DS9 available in a
known location.
  warnings.warn(ds9_warning)
```

and *afterwards*, on `ds9 = vip.vip_ds9.Ds9Window()`, I got the `TypeError` you mentioned.

**Comment by carlgogo** [comment]
> The old version 7.5, which I used before, had the space in the filename, they seem to have changed it.
> Did you try to `File > XPA > Connect`?

Yes I tried that

**Comment by carlgogo** [comment]
> BTW, did you silence the `warnings` somehow?

No, that seems to be ``pyds9`` code

**Comment by carlgogo** [comment]
For the record, I solve my issues after renaming ``SAOImageDS9`` to ``SAOImage DS9``.
