### ISSUE TITLE
Non ADI function

### ISSUE THREAD

**Issue by jmilou** [vortex-exoplanet/VIP#35]
Dear Carlos,

I was looking for a non ADI reduction and could not find this functionality in vip. Did you implement this functionality ? 
By non ADI I mean, no star subtraction, only derotation and stacking of the frames, optionally after subtracting the median in annuli to get rid of the radial gradient in the final image. 
This is quite important in a data reduction pipeline, as it very often yields the best reduction in the background limited region. 

Julien

**Comment by carlgogo** [comment]
Hi Julien,

Cube derotation and collapsing are of course implemented in VIP. Check out this functions *vip.calib.cube_derotate* and *vip.calib.cube_collapse*.

The functionality you mention for removing the radial gradient in the final image can be implemented. Just to make sure I understood, we operate on the final image? This could be done like this (pseudo-code):
   
`function(2d_array):
    partition the frame in annular regions
    obtaining the median of each annulus
    subtraction of the median from the corresponding annulus`

If you agree with this I'll include the functionality in *vip.calib.cube_collapse* as optional.

Cheers,
Carlos

**Comment by jmilou** [comment]
Hi Carlos, 

Yes I had seen the function cube_derotate and cube_collapse, thanks.
Removing the radial gradient is more efficient done in individual frames, before collapsing the cube. I do it in annuli of 1px. Apart from that, your pseudo-code is fine. 

Thanks
Julien

**Comment by carlgogo** [comment]
Then it makes sense to have it as a standalone function receiving as input a cube (and optional parameter the annulus width). I'll include it for next commit of VIP.

**Comment by carlgogo** [comment]
Hi Julien. This has been here for a while. I'll close it the thread. Let me know if you want to contribute to VIP the radial gradient subtraction. Cheers
