### ISSUE TITLE
possible update: in negfc/utils_negfc

### ISSUE THREAD

**Issue by KristinaDavis** [vortex-exoplanet/VIP#355]
import statement fails: from matplotlib.pyplot import plot, xlim, ylim, hold,  axes, gca, show
(later in code, line 108)
    if display:        
        #hold(True)
        plot(u,v,'ks',x,y,'r')        
 
'hold' is depreciated in pyplot > 2.0, see https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hold.html

I am currently using matplotlib=3.0.2. I can just delete those lines from my code, which I _think_ will revert to the default of automatically holding unless you clear the axis (as per the documentation). However, it might be worth considering updating for those using later packages of matplotlib. 

Thanks!

**Comment by carlgogo** [comment]
Unfortunately, VIP is still using matplotlib ~= 2.2 (see requirements.txt), and the import statement you mention seems to work fine in this case. Of course, it'd be great to make VIP compatible with matplotlib > 3.0. That will require checking all functions that import from matplotlib to see if there are fixes to be applied. Would you like to contribute, we definitively welcome PRs! :)

**Comment by carlgogo** [comment]
I hope you managed to install VIP. I wanted to let you know, before closing this issue, that VIP now works with ``matplotlib`` 3. Cheers

**Comment by KristinaDavis** [comment]
Thanks!


Kristina K. Davis, PhD.
Astronomy & Astrophysics Postdoctoral Fellow
National Science Foundation
University of California, Santa Barbara
k_davis@physics.ucsb.edu
kristinadavis.weebly.com
