### ISSUE TITLE
Scaling in pca_rdi_annular

### ISSUE THREAD

**Issue by rmjc** [vortex-exoplanet/VIP#36]
Hi all, 

I'm a bit puzzled by the scaling steps in pca_rdi_annular, lines 161 and 162:

matrix = scale(matrix, with_mean=True, with_std=True)
data_ref = scale(data_ref, with_mean=True, with_std=True) 

With a 35-frame science cube and 40 reference stars (each themselves 35-frame cubes), I make a contrast curve via pca_rdi_annular. For simplicity, I ignore the throughput by setting it to 1.0 everywhere. Attached are the resulting contrast curves with and without the scaling lines. The contrast curve with the scaling is considerably worse. 

![contrast_with_rescaling](https://cloud.githubusercontent.com/assets/5223860/13412539/c8aa1fd6-def8-11e5-9156-99acfd38cf7b.png)
![contrast_without_rescaling](https://cloud.githubusercontent.com/assets/5223860/13412543/cdabe06e-def8-11e5-866e-dc028e602865.png)

For what it's worth, I'm in the i' band, with low (<10%) Strehl and no coronagraph.

**Comment by carlgogo** [comment]
This does not surprise me. With a single small cube (<100 frames) there is little point in using *pca_rdi_annular*. This is definitely not the scenario for which I implemented this function. It will be helpful to read the function internal documentation and if you need more details please drop me an email. 

Cheers,
Carlos
