### ISSUE TITLE
Flux conservation in vip.calib.cube_px_resampling

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/VIP#38]
Hi @carlgogo 

I think it would be better that vip.calib.cube_px_resampling conserves the total flux in the image. You basically just need to divide the pixel value by the square scaling factor to make it work.

Cheers,
Olivier.

**Comment by carlgogo** [comment]
Hi @oabsil 
Thanks for the suggestion. I'll take care of that in the next commit.
Carlos
