### ISSUE TITLE
Question about standard deviation in SNR computation

### ISSUE THREAD

**Issue by timothygebhard** [vortex-exoplanet/VIP#395]
Hi! :)

Quick question about the way you compute the `snr()` in `metrics/snr_source.py`: On [line 319](https://github.com/vortex-exoplanet/VIP/blob/master/vip_hci/metrics/snr_source.py#L319), when you compute the `snr_vale`, you are basically directly implementing equation (9) from [Mawet et al. (2014)](https://arxiv.org/pdf/1407.2247.pdf), correct? In their paper, they write that $s_2$ in the denominator is the "_empirical_ standard deviation". That doesn't seem to be a standard statistics term, but from equation (8) in the paper I concluded that what they mean by this appears to be the _sample_ standard deviation using [Bessel's correction](https://en.wikipedia.org/wiki/Bessel%27s_correction). 
However, in your code, you use `ndarray.std()`, which by default computes the standard deviation _without_ this correction factor (you need to pass the `ddof=1` argument to enable that).

Do you have any deeper insight what's actually correct here? That is, should we use the biased (current implementation) or unbiased (would need the additional `ddof=1` argument) estimator for the standard deviation of the "noise apertures" when computing the SNR?

Thanks in advance, and cheers,
— Timothy

**Comment by carlgogo** [comment]
Hi there, yes the ``snr()`` function implements eq. 9 from Mawet et al. (2014). We apply the ``(n-1)`` correction by getting the standard deviation of the background apertures without the test resolution element or "over the remaining n2 = n − 1 resolution elements at radius r" (see [line 317](https://github.com/vortex-exoplanet/VIP/blob/master/vip_hci/metrics/snr_source.py#L317)). The documentation of ``numpy.std()`` says: "The standard deviation computed in this function is the square root of the estimated variance, so even with ddof=1, it will not be an unbiased estimate of the standard deviation per se".

I'm not sure that using ``ddof=1`` will be more correct but I'm open to discuss this further. In practice, using ``ddof=1`` doesn't change much, see the attached figure showing the S/N maps computed with the current implementation and with ``ddof=1``, and their difference. 

@dmawet @oabsil, any thoughts?

![image](https://user-images.githubusercontent.com/12588564/56890437-b9110c00-6a79-11e9-86a5-7fbabcc0ba43.png)

**Comment by oabsil** [comment]
In the definition of the t test, s2 should be computed as the unbiased standard deviation, with the Bessel correction (see https://en.wikipedia.org/wiki/Student%27s_t-test#Equal_or_unequal_sample_sizes,_equal_variance). This is also suggested in Eq. 8 of the paper (where you see the n_2-1 denominator in the expression of s2). So I would suggest to use ddof=1, even though the difference is generally small.

**Comment by carlgogo** [comment]
Ok, added the ``ddof=1``. Then let's close this.
