### ISSUE TITLE
Minor bug in the reject_outliers() prototype.

### ISSUE THREAD

**Issue by owertz** [vortex-exoplanet/VIP#4]
Hi Carlos,
Hi Valentin,

It seems that there is a minor bug at line 577 of **vip.calib.badpixremoval.py**. In the function **reject_outliers()** prototype, a non-default argument follows a default argument.

Cheers,
Olivier

**Comment by VChristiaens** [comment]
Hi Olivier, hi Carlos
Thanks for pointing this out, I just modified it at the last minute yesterday night when adapting my version of the module to the VIP package. Sorry for not having checked that little change.
The best thing to do is to invert the order of the arguments "m" and "test_value", which I did in the last commit, and pulling request now.
While in my previous version of reject_outliers "test_value" was optional, now the whole point of the function is to determine if test_value is an outlier with respect to data, so it can't be optional any more.

Cheers,
Valentin

**Comment by carlgogo** [comment]
Sounds good. Pull request accepted.
