### ISSUE TITLE
Negative values in cube resampling

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/VIP#40]
Hi @carlgogo 

I've just noticed that, when using the function vip.calib.cube_px_resampling with a cube that has zero background, but that contains no negative value, you get several negative values in the output cube. I assume that this is due to the interpolation, but it can have significant side effects if one is not aware of that. Not sure what to do. Maybe just add a warning in the docstring?

Cheers,
Oli.

**Comment by carlgogo** [comment]
@oabsil , I recreated your scenario  by injecting a PSF in a cube of zero frames. Indeed negative values appeared where the injected PSF borders the zero background, so it seems to be caused by the interpolation. I added a note in the docstring of the function!
