### ISSUE TITLE
VIP tutorial does not match the latest version 

### ISSUE THREAD

**Issue by ChristianAdam280** [vortex-exoplanet/VIP#403]
Hello,

First i want to thank you for all the effort you put in this project. This is very much appreciated.
However, I installed the latest version of VIP (version: 0.9.10) and tried to follow the tutorial to get into it, but  after importing the package successfully i get an error right when i try to do:

plots = vip.var.pp_subplots

Traceback (most recent call last):

  File "<ipython-input-60-ad93a4590fcb>", line 1, in <module>
    plots = vip.var.pp_subplots

AttributeError: module 'vip_hci.var' has no attribute 'pp_subplots'

This continues through almost all modules.

Can you help, please.
Best regards

**Comment by carlgogo** [comment]
Hi @ChristianAdam280, thank you and sorry for the slow reply. I was in holidays. You're totally right, the tutorial was not up to date wrt VIP. Please pip upgrade VIP (to v0.9.11) and check again the repository with the updated tutorial. Cheers!
