### ISSUE TITLE
Simplex: changing the f_range affects the results

### ISSUE THREAD

**Issue by arainot** [vortex-exoplanet/VIP#409]
Hi @carlgogo,

Using the latest version of VIP, I have noticed that changing the `f_range` in the `vip_hci.negfc.firstguess` function changes the results of Simplex quite dramatically (from 30 to 60%). I ran some tests where I injected a companion with known spectrum into an image and then when I tried to retrieve the flux (knowing its value), I noticed that using a fine range (steps of 20 or 30) were resulting in a wrong flux value. However if I took a range with larger steps (~100), then it would find the correct value. Using higher steps again resulted in the flux being not correct. 
With an older version of VIP, this difference was not as prominent. Do you have an insight as to what changed recently with how VIP computes the simplex optimisation and do you have a recommendation as to what range would be optimal to use?

**Comment by carlgogo** [comment]
Hi @arainot,

No I don't know what is the cause for this behaviour and unfortunately the ``NEGFC`` subpackage hasn't been integrated in the automated testing (tests folder in the root of the ``VIP`` package). 

Many small changes have been introduced to the ``NEGFC`` functions over the last two years. Finding the "problem" would require a thorought testing using the "older" version of ``VIP`` against the current one, paying carefult attention to the versions of the requirements (``scipy`` in this case). 

Would you be available for investigating this behaviour? If yes, I'd be glad to provide some guidance.

**Comment by arainot** [comment]
Unfortunately I do not have the time at the moment to debug this issue. I will try to see where the problem originates from and let you know if I find anything.

**Comment by arainot** [comment]
Hi @carlgogo,

We identified the issue and were able to resolve it on our part using the latest version of VIP available. It works as intended now! We had to modify the f_range to include all possible values.

**Comment by oabsil** [comment]
Hi @arainot 
Before closing the issue, you should make sure to submit your changes (if any) as a pull request, so that everyone can benefit from the suggested correction. Even if the code doesn't need to be fixed, changing the documentation within the code of associated function(s) could make it easier for future usage.
Happy to see that the problem was not too deep!
Thanks!

**Comment by arainot** [comment]
Hi @oabsil,
Sure, we just need to make sure the user sets a high maximum guess value for the f_range in the simplex function, as inputting lower values than the real one will result in a bad estimation of the flux.
