### ISSUE TITLE
Bug in cube_detect_badfr_pxstats

### ISSUE THREAD

**Issue by jmilou** [vortex-exoplanet/VIP#41]
Dear Carlos, 

I found a little bug in vip/calib/badframes.py
On line 85, in cube_detect_badfr_pxstats :
    `mean_smooth = pn.rolling_median(mean_values, window , center='True')`
It should be  
    `mean_smooth = pn.rolling_median(mean_values, window , center=True)`

Cheers
Julien

**Comment by carlgogo** [comment]
Thank Julien, this was fixed!
