### ISSUE TITLE
Problem with speckle-based recentering function

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/VIP#413]
Problem spotted by Dimitri Mawet (@ Lyot conference):

line 1245 in recentering.py
should read     
cube_sci_lpf = cube_filter_lowpass(cube_sci_hpf, ‘gauss’,
                                      fwhm_size=int(fwhm * min_spat_freq), verbose=False)

Could someone please double check and update accordingly? (not sure the 'int' is needed)

**Comment by VChristiaens** [comment]
Problem solved in the last pull request I sent.
The int() is indeed not necessary. I adapted the description of the filter_high/low_pass functions.
