### ISSUE TITLE
readme.rst should be README.rst

### ISSUE THREAD

**Issue by MartynBrake** [vortex-exoplanet/VIP#42]
Hello,

Installing on ubuntu 14 and get the following:
`
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    readme = open('README.rst').read()
IOError: [Errno 2] No such file or directory: 'README.rst'`

Did this and sorted it out:
`mv readme.rst README.rst`

Not a biggy, but thought you should know.

Cheers,
Martyn

**Comment by carlgogo** [comment]
Thanks Martyn, this has been fixed in the last version!

**Comment by MartynBrake** [comment]
Latest version (0.5.1) complained of this issue again.

Cheers,
Martyn

**Comment by carlgogo** [comment]
Hi Martyn, yes for some reason the filename kept turning lowercase. I decided to keep it lowercase and also re-wrote the setup.py. Check out the 0.5.2 release.

Cheers,
Carlos
