### ISSUE TITLE
Should we be using the Gelman–Rubin statistic in negfc with MCMC?

### ISSUE THREAD

**Issue by rmjc** [vortex-exoplanet/VIP#432]
Hi all, 

The emcee documentation ([here](https://emcee.readthedocs.io/en/stable/tutorials/autocorr/)) mentions "you should not compute the G–R statistic using multiple chains in the same emcee ensemble because the chains are not independent." Perhaps it would be better to use the autocorrelation instead. I'm curious what you all think.

Becky

**Comment by VaChristiaens** [comment]
Hi Becky,
Thanks for the suggestion! And very sorry for the shamefully long delay in the reply! After a quick look at the link you sent, I agree it seems more appropriate to use the integrated autocorrelation. I'd be interested in having your insight @oabsil : do you remember discussing other tests than Gelman-Rubin with Olivier Wertz when he implemented the MCMC? Was it chosen as an easier/faster to compute proxy for convergence? If it is easy to implement/fast to compute it is maybe worth adding an option to rather use the integrated autocorrelation?
@rjmc Have you already made any tests using the autocorrelation in the MCMC by any chance? 
Best wishes,
Valentin

**Comment by VChristiaens** [comment]
The suggestion of an autocorrelation-time based convergence criterion has now been implemented (since VIP v1.0.0) in `mcmc_negfc_sampling`. It can be activated by setting `conv_test='ac'` (instead of default value `'gb'`). Thanks again for the suggestion!
