### ISSUE TITLE
jupyter notebook example does not work

### ISSUE THREAD

**Issue by epantin** [vortex-exoplanet/VIP#436]
I loaded vip-extras from Githubn, and tried to run the notebook. 

The line 
'plots = vip.var.pp_subplots'
crashes :
'AttributeError: module 'vip_hci.var' has no attribute 'pp_subplots'

Since the notebook has been written for version 0.9.8, if it shoukld not be updated for 0.9.11

**Comment by VChristiaens** [comment]
Hi @epantin,
Could you be specific on how you obtained vip-extras?
[Here](https://github.com/carlgogo/VIP_extras) I see the jupyter notebook is up-to-date with versions 0.9.10/0.9.11, where vip_hci.var.pp_subplots is not used anymore.
Cheers,
Valentin

**Comment by VChristiaens** [comment]
Closing as the jupyter notebook tutorials have been updated for VIP versions 1.0.0 onwards, and do not show this error.
