### ISSUE TITLE
bug in cube_recenter_dft_upsampling with subi_size=None

### ISSUE THREAD

**Issue by jmilou** [vortex-exoplanet/VIP#44]
There is a minor bug in file "VIP/vip/calib/recentering.py", line 646, in cube_recenter_dft_upsampling:
    x[0] = cx

UnboundLocalError: local variable 'cx' referenced before assignment

This happens when the option subi_size is set to None.  It can be easily corrected by taking the line 
cy, cx = frame_center(array[0])
out of the if condition like this

   cy, cx = frame_center(array[0])
    if subi_size is not None:
        size = int(fwhm*subi_size)
        y1, x1 = _centroid_2dg_frame(array_rec, 0, size, cy_1, cx_1)
        array_rec[0] = frame_shift(array_rec[0], shift_y=cy-y1, shift_x=cx-x1)
        x[0] = cx-x1
        y[0] = cy-y1
    else:
        x[0] = cx
        y[0] = cy

Cheers
Julien

**Comment by carlgogo** [comment]
Thanks for catching this one Julien!
