### ISSUE TITLE
LOCI for ADI is missing distance threshold

### ISSUE THREAD

**Issue by mileslucas** [vortex-exoplanet/VIP#442]
I was reading through the LOCI implementation and I got confused looking through the ADI implementation-https://github.com/vortex-exoplanet/VIP/blob/df97f3037f6f43dfa13d7d0b12897d9f014517a9/vip_hci/leastsq/leastsq.py#L349-L383

It seems like the distances in the reference are calculated but never used. That is, the threshold distance is never calculated, which means the masking will never filter any frames. Is this a bug, or is the `dist_threshold` only supported for SDI?

**Comment by VChristiaens** [comment]
Thanks for pointing this out @mileslucas. I think you are right. You mean lines 483 to 486 seem to be missing at line 361 right?

**Comment by mileslucas** [comment]
yes L483-486 seems missing!
