### ISSUE TITLE
Unable to use the madi subroutines

### ISSUE THREAD

**Issue by trisha-bhowmik** [vortex-exoplanet/VIP#449]
Hello everyone,

I have been trying to perform ADI on a data cube. When I use "vip.madi.adi(cube_crop, rot, mode='fullfr')" I get an error saying "AttributeError: module 'vip_hci' has no attribute 'madi'".

When I try to import madi "from vip_hci.madi import *" I get an error saying "ImportError: cannot import name 'get_annulus' from 'vip_hci.var' (/home/tbhowmik/miniconda3/lib/python3.7/site-packages/vip_hci/var/__init__.py)"

Has there been any update in the calling sequence?
Please suggest a way to solve this issue.

Best regards,
Trisha Bhowmik

**Comment by VChristiaens** [comment]
Hi @trisha-bhowmik,

The madi module was replaced by medsub in pull request #203 (v0.9.7). It now includes the option to perform median-SDI as well (hence the name change).
The var.get_annulus() was also removed in pull request #281  (v0.9.8). This was made redundant by the var.get_annulus_segments(), whose default behavior takes a full annulus.

If you run into similar issues in the future, please don't hesitate to check the documentation here: https://vip.readthedocs.io/en/latest/

Note that we are currently converging towards a version v1.0.0, and the documentation will soon be updated accordingly. There will be an extra subpackage, some bug fixing and new options in existing routines, but there should not be any significant change in existing modules and routines (names and mandatory arguments will stay the same) in v1.0.0.
