### ISSUE TITLE
Minor bug in vip.negfc.confidence

### ISSUE THREAD

**Issue by jmilou** [vortex-exoplanet/VIP#45]
Dear Carlos, 

When we use the keyword title in the function vip.negfc.confidence, it generates an error line 933 (and probably 937 too) because the variable fig has no title attribute:

  File "/vip/negfc/mcmc_opt.py", line 933, in confidence
    fig.title(title+'   '+msg.format(mu[j],sigma[j]),

AttributeError: 'Figure' object has no attribute 'title'

This is probably a minor bug. Looking a bit on the way to do it, you can probably use instead
ax.set_title(title+'   '+msg.format(mu[j],sigma[j])

Cheers
Julien

**Comment by carlgogo** [comment]
Thanks @jmilou , I changed the fig.title to fig.suptitle, that should fix it.
