### ISSUE TITLE
Error running cube_inject_companions in 02_adi_negfc_cc tutorial 

### ISSUE THREAD

**Issue by rbowru** [vortex-exoplanet/VIP#460]
Hello,

I encountered another error while running new version of the 02_adi_negfc_cc tutorial. I'm getting an error when running the cell with:

cubefc = cube_inject_companions(cube, psf_template=psfn, angle_list=angs, flevel=400, plsc=pxscale_naco, 
                                rad_dists=[30.5], theta=240, n_branches=1, imlib=imlib_rot)

Here's a screenshot of the error, and it states that the "Image transformation library not recognized"

Thank you! 
![image](https://user-images.githubusercontent.com/66432460/134989692-94f71719-f825-443e-bca8-c609236568c8.png)

**Comment by rbowru** [comment]
I solved a similar problem in section 4 of the code by changing "import opencv" to "import cv2".

**Comment by VChristiaens** [comment]
Hi,
From the quoted lines of `fakecomp.py` in the error message, my guess is that the issue stems from the use of an older version of VIP. Would upgrading to the latest version solve the issue?

**Comment by VChristiaens** [comment]
Thanks for noticing the `import opencv` line, this will be fixed in the next update of the notebook.

**Comment by rbowru** [comment]
Thanks! An update helped!   Doing a fresh git clone of the VIP repository fixed this issue for me.
