### ISSUE TITLE
Question about how to avoid static walkers

### ISSUE THREAD

**Issue by rbowru** [vortex-exoplanet/VIP#471]
I'm trying to perform an MCMC to extract the position and flux, but I'm having an issue with my walkers.  Rather than fluctuating a small amount around a central value like in the tutorial, they seem to lock onto one value and statically stay there.  I've included a couple of my walker plots below to show you what I mean.

Have you ever seen something like this before (is this normal)?  Are there any settings you would suggest adjusting to avoid this? 

Here's the walker and corner plots from one of the many runs that I've tried that shows the static walker issue. 
![image](https://user-images.githubusercontent.com/66432460/138141544-67029fd5-3af9-4da1-bb95-536f898ceb3c.png)
![image](https://user-images.githubusercontent.com/66432460/138141558-7d2a3bae-de4b-4c58-b428-f52f8b5457f3.png)

Here's the best run that I've done, but the walkers are still going static after 70 steps.  Running for longer doesn't change the flat line results. 
![image](https://user-images.githubusercontent.com/66432460/138141578-cef864dc-cc91-4b8e-98a3-ff7a85a1c62a.png)
![image](https://user-images.githubusercontent.com/66432460/138141601-dedee33f-9f6e-4c06-8d5c-7a262003ec71.png)

Here's a run I did with only 10 walkers, so you can see what's happening in a clearer way:
![image](https://user-images.githubusercontent.com/66432460/138141615-35ff5e6f-ceff-44ac-89b8-5d3e2f5fe3a3.png)

**Comment by rbowru** [comment]
Thanks for your suggestions!  I tried a few versions of setting mu_sigma = (0,1) with no change (as I now see was expected).  I just noticed your second comment, and I'll try that now.

**Comment by rbowru** [comment]
Setting `mu_sigma = True` worked!  Thank you!  I've been struggling with this issue for over a month, and this was a really helpful suggestion. 

Here's my current walker plot:
![image](https://user-images.githubusercontent.com/66432460/140551117-5a0d1600-900b-4908-a56c-c45c4377ef18.png)

**Comment by VChristiaens** [comment]
Glad to read the suggestion worked! Will do some more tests and possibly change the default behaviour of `mcmc_negfc_sampling` in a future release if the uncertainty estimate is systematically more reliable.
