### ISSUE TITLE
vip.metrics.contrast_curve() discrepancy 

### ISSUE THREAD

**Issue by rbowru** [vortex-exoplanet/VIP#478]
Hello, 

I noticed a significant discrepancy between the old and current version of VIP while making contrast curves using vip.metrics.contrast_curve().   Here's the same data set while running vip.metrics.contrast_curve() with the same settings (except for the imlib called). 

I've also noticed that you removed the option for setting the imlib in vip.metrics.contrast_curve() -- was this intentional?  Imlib is still left as a possible variable in the comments for the function.

Contrast curve generated with VIP 1.0.0 using the imlib_rot = 'ndimage-fourier'
![image](https://user-images.githubusercontent.com/66432460/146616747-6bef7011-a79e-4417-b244-571414c240b2.png)

Contrast curve generated with the current master branch version of VIP:
![image](https://user-images.githubusercontent.com/66432460/146616763-f6c03dc1-b19a-4e84-a3d0-8208bcdecedb.png)

**Comment by VChristiaens** [comment]
Thanks for noting this. The problem should now be solved in the master branch with the latest pull request (#481). There was an issue with the FFT-based shift of injected psf images in the throughput routine (used in turn in the contrast curve).

Note that the `imlib` keyword is still valid, as explained in the `**algo_dict` argument's description. It had to be explicitly removed from the optional arguments list of the contrast curve routine though to avoid a duplicated argument bug.
