### ISSUE TITLE
Good way to use VIP

### ISSUE THREAD

**Issue by sbrems** [vortex-exoplanet/VIP#54]
Hello,

I have a question about optimally using the VIP code. If you have a none-detection image (as usually ;) ), is it a good idea to proceed the following ways (computation time doesn't matter as a lot can be parallelized and we have many idle cores):

For each FWHM-wide annulus:
1. Insert one fake planet at a random angle.
2. Optimize for this fake planet the number of  PCs only on this annulus (possible in version 0.5.3)
3. Repeat 1 and 2 for many times and find the median of optimal PCs.
Now we have an optimal number of PCs for each annulus. So
4. For each annulus use the optimal number of PCs found before and do PCA/LLSG (possible in version 0.5.3)
5. Calculate the contrast curve by including and recovering different fakes for each annulus using the number of PCs found before (done automatically by your pipeline)

Thank you,
Stefan

**Comment by carlgogo** [comment]
Hi Stefan, this sounds reasonable, but take into account that the # of PCs will depend on the brightness of the injected companion on step 2. So, I'm not sure how optimal is this value. There is a discussion about this on Meshkat et al 2014.
