### ISSUE TITLE
Bug in new annulus mode (v.05.4)?

### ISSUE THREAD

**Issue by sbrems** [vortex-exoplanet/VIP#57]
Hey,
I think there is a bug in the new vip.pca.pca_ad_annular  mode where you can give ncomp as a list matching the number of annuli (then every annulus get's its own number of PCs):
I get an error in utils.py on line  360  [ if ncomp>min(matrix.shape[0],matrix.shape[1])]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

if I print ncomp there it is the list which explains the error.

Tracing back led me to:
in pca_local there is a function get_eigenvectors differentiating different cases , i.e. ncomp=None (l.579 ff). I guess there should also be a case for ncomp being a list?
However I didn't manage to come up with a (simple) solution on my own :(

Thank you,
Stefan

**Comment by carlgogo** [comment]
Hi Stefan, I cannot reproduce your error. Please copy and paste the full error traceback and I'll try to find what's the reason. 
C.

**Comment by sbrems** [comment]
Hey, here is the output: I also printed ncomp and array.shape at the end

`PCA will be done locally per annulus and per quadrant

Annulus 1, PA thresh = 61.75, Inn radius = 0.00, Ann center = 2.00 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-2852b45fc06b> in <module>()
----> 1 reduce()

/disk1/brems/GJ1046_Kuerster/vip_analysis/analyse_hip.pyc in reduce(side, n_comp_dir, n_comp_fn, pc)
    289         reduced_image = vip.pca.pca_adi_annular(cube,angs,fwhm=fwhm,ncomp=pc_list/10,
    290                                                 asize=asize,delta_rot=delta_rot,
--> 291                                                 quad=True,debug=True,min_frames_pca=np.max(pc_list))
    292         contr = vip.phot.contrast_curve(cube,angs,psf_norm,fwhm,pxscale,starphot,
    293                                         sigma=5,nbranch=1,algo = vip.pca.pca_adi_annular,

/disk1/brems/my_python/VIP/vip/pca/pca_local.pyc in pca_adi_annular(cube, angle_list, radius_int, fwhm, asize, delta_rot, ncomp, svd_mode, nproc, min_frames_pca, tol, scaling, quad, collapse, full_output, verbose, debug)
    344                                         fwhm, pa_thr, scaling, ann_center,
    345                                         svd_mode, ncompann, min_frames_pca, tol,
--> 346                                         debug, verbose)
    347 
    348                 for frame in xrange(n):

/disk1/brems/my_python/VIP/vip/pca/pca_local.pyc in do_pca_loop(matrix, yy, xx, nproc, angle_list, fwhm, pa_threshold, scaling, ann_center, svd_mode, ncomp, min_frames_pca, tol, debug, verbose)
    490                                pa_threshold, scaling, ann_center,
    491                                svd_mode, ncomp, min_frames_pca, tol,
--> 492                                debug)
    493             residualarr.append(res[0])
    494             ncomps.append(res[1])

/disk1/brems/my_python/VIP/vip/pca/pca_local.pyc in do_pca_patch(matrix, frame, angle_list, fwhm, pa_threshold, scaling, ann_center, svd_mode, ncomp, min_frames_pca, tol, debug)
    560     curr_frame = matrix[frame]                     # current frame
    561 
--> 562     V = get_eigenvectors(ncomp, data, svd_mode, noise_error=tol, debug=False)
    563 
    564     transformed = np.dot(curr_frame, V.T)

/disk1/brems/my_python/VIP/vip/pca/pca_local.pyc in get_eigenvectors(ncomp, data, svd_mode, noise_error, max_evs, data_ref, debug)
    605     else:
    606         # Performing SVD/PCA according to "svd_mode" flag
--> 607         V = svd_wrapper(data_ref, svd_mode, ncomp, debug=False, verbose=False)
    608 
    609     return V

/disk1/brems/my_python/VIP/vip/pca/utils.py in svd_wrapper(matrix, mode, ncomp, debug, verbose, usv)
    358         print(msg.format(ncomp, ratio_cumsum[ncomp-1]))
    359 
--> 360     if ncomp>min(matrix.shape[0],matrix.shape[1]):
    361         msg = '{:} PCs can be obtained from a matrix with size [{:},{:}].'
    362         msg += ' Increase the size of the patches or decrease the number of'

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> /disk1/brems/my_python/VIP/vip/pca/utils.py(360)svd_wrapper()
    359 
--> 360     if ncomp>min(matrix.shape[0],matrix.shape[1]):
    361         msg = '{:} PCs can be obtained from a matrix with size [{:},{:}].'

ipdb> p ncomp, matrix.shape
(array([ 3. ,  3.4,  3. ,  4.3,  4.1,  4.1,  4.1,  4.1,  4.1]), (92, 17))
`

The input is:

`vip.pca.pca_adi_annular(cube,angs,fwhm=fwhm,ncomp=pc_list,
                                                asize=asize,delta_rot=delta_rot,
                                                quad=True,debug=True,min_frames_pca=np.max(pc_list))`

with
` p cube.shape,angs.shape, fwhm, pc_list, asize, delta_rot
((419, 75, 75), (419,), 4.782923313505, array([30, 34, 30, 43, 41, 41, 41, 41, 41]), 1, 0.5)
`
Let me know if you need more info
Thanks a lot for your effort,
Stefan

**Comment by carlgogo** [comment]
Hi Stefan, sorry for the delay. The problem is that the function needed ``ncomp`` as an integer or a list (a Python list) and you were using pc_list which is a 1d numpy array. It wouldn't hurt to accept a 1d numpy array as well, so I just made the modifications and your code should run fine. C.

**Comment by sbrems** [comment]
Hey Carlos,this is something I could have come up on my own :( But thanks a lot for looking into it and solving the problem.

**Comment by carlgogo** [comment]
Sure Stefan ;) You're welcome!
