### ISSUE TITLE
vip.calib.cube_px_resampling vs vip.calib.frame_px_resampling

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/VIP#58]
Hi @carlgogo 

It looks like these two functions have different behaviors regarding flux conservation. For the cube, the flux is preserved, while for the frame, the flux is modified according to the square pixel size ratio. The function vip.calib.frame_px_resampling should be modified to have the same behavior as the other one.

Cheers,
Olivier

**Comment by carlgogo** [comment]
Hi @oabsil, are you looking at the last version of VIP? 
https://github.com/vortex-exoplanet/VIP/blob/master/vip/calib/rescaling.py#L111

**Comment by oabsil** [comment]
My bad, once again my local version of VIP was not up to date (shame on me). --Olivier
