### ISSUE TITLE
Extraneous getargspec in vip_hci.config.utils_conf.py

### ISSUE THREAD

**Issue by meressler** [vortex-exoplanet/VIP#609]
While installing on a fresh python-3.11.4, I got an error about getargspec not being available from the inspect module. I gather getargspec has been deprecated in favor of fullgetargspec. However, importing getargspec in line 20 is pointless as the only occurrence of getargspec is in some commented out code in line 251. I suggest deleting getargspec from the import (and maybe deleting the dead code around line 251).

**Comment by IainHammond** [comment]
i noticed this too and just deleted the getargspec import. I believe @Eixalde updated that part of the code so it should no longer be needed at all right?
