### ISSUE TITLE
VORTEX transmission in contrcurve.py

### ISSUE THREAD

**Issue by maddalenareggiani** [vortex-exoplanet/VIP#64]
In contrcurve.py the vortex transmission is applied to the final contrast curve and not to the throughput. Therefore it does not appear in the end in the throughput vector and in the corresponding plot (as well as in the student-t corrected contrast curve).
Since at the moment it is applied directly to the curve and not to the throughput, I also think it is misleading to call it transmission, as it is defined as cont_curve_samp = cont_curve_samp*trans_interp (instead of cont_curve_samp = cont_curve_samp/trans_interp). 
I would keep calling it transmission, but I would apply it directly to the throughput  (thruput_interp_attenuated=thruput_interp * trans_interp), so that both cont_curve_samp and cont_curve_samp_corr would then be affected.

Cheers,
Maddalena

**Comment by carlgogo** [comment]
Hi Maddalena, I agree with you. The changes will be made in the next update. 
C.
