### ISSUE TITLE
The call of a module object raises an error in vip/pca/pca_fullfr.py

### ISSUE THREAD

**Issue by owertz** [vortex-exoplanet/VIP#7]
Hi Carlos,

When **get_snr()** is called, it seems that, at line 178 in vip/pca/pca_fullfr.py, one tries to call **vip.phot.snr** which is a module and not a function or method. As a consequence, it raises a TypeError exception because of module object is not callable. I guess that one should call **vip.phot.snr.snr_ss()** or **snr_peakstddev()** instead. Which one of these do you advocate ?

For information: vip.pca.pca_optimize_snr() --> grid() --> get_snr() --> phot.snr

Cheers,
Olivier

**Comment by carlgogo** [comment]
Hi Olivier, 

Thanks for spotting this bug. Indeed, I changed this recently but I was calling the module instead of the function snr_ss() which takes into account resolution elements and small sample statistics correction. We need automated testing :/

I'll commit the fix now. 

Cheers,
Carlos
