### ISSUE TITLE
The true SNR of a companion

### ISSUE THREAD

**Issue by VChristiaens** [vortex-exoplanet/VIP#70]
This topic was briefly mentioned during a recent telecon. It might be useful to dwell a bit more on it:

The SNR of a companion detection computed with snr_ss() is inconsistent with the SNR of the companion that is estimated with the ratio of the NEGFC contrast to the noise in the local annulus (that can be visualized for example when plotting the companion contrast on top of the 5-sigma contrast curve). Several factors can explain this discrepancy: (i) throughput (only considered in the second case); (ii) a possible underlying speckle contamination (that could artificially enhance the SNR in the first case); (iii) the local noise estimate, which is estimated on the whole annulus after removing the companion itself in the second case, but computed on a truncated annulus in the first case (this effect gets significant only for very close-in companions).

For example, in the case of companion HD 206893 B (Milli+2017, accepted), snr_ss() would yield a SNR of ~10, while based on the NEGFC contrast and noise estimate on the local annulus, the SNR becomes ~6  (for the same PCA-ADI algo and npc used). In the paper, we conservatively quoted the second value. 

The first one is a pure signal detection theory SNR which can be computed directly on the final PCA-processed frame, while the second requires also the initial cube to inject negative fake companions. So you'd inherently expect to obtain different values. The question is: which value makes more sense to be quoted in a paper to reflect the significance of the detection?

**Comment by carlgogo** [comment]
@VChristiaens We've discussed this internally so I'll close this issue. It's up to you if you want to share here the results of your tests. In this case it could be nice to include a paragraph about that in the documentation and/or tutorial.
