### ISSUE TITLE
small sample correction in vip.phot.contrast_curve

### ISSUE THREAD

**Issue by maddalenareggiani** [vortex-exoplanet/VIP#71]
Hi Carlos,

since the small sample correction ss_corr is defined as:
ss_corr = np.sqrt(1 + 1/(n_res_els-1))
I think sigma should be multiply to it, and not divided, meaning
        sigma_corr = stats.t.ppf(stats.norm.cdf(sigma), n_res_els)*ss_corr
instead of 
        sigma_corr = stats.t.ppf(stats.norm.cdf(sigma), n_res_els)/ss_corr

Cheers,
Maddalena

**Comment by carlgogo** [comment]
As we discussed in person recently, this will be fixed in next release. Thanks Maddalena.
