### ISSUE TITLE
Contrast_curve noise per annulus

### ISSUE THREAD

**Issue by astropatel** [vortex-exoplanet/VIP#73]
Hi Carlos,

I ran into another problem when calculating the contrast_curve information.

On line 154 of contrcurve.py, when noise_samp is being defined:

> noise_samp = noise_samp[cutin1:]

 I run into  the following error:
> TypeError: only integer scalar arrays can be converted to a scalar index

It seems that cutin1 is a one element array. The same goes for the cutin2 when it's defined a couple lines later. I have attached the full traceback below with printed values of each array. I am performing this on simulated data, so perhaps that is the reason? In which case, I am unsure how to proceed.

![image](https://cloud.githubusercontent.com/assets/3648312/23821722/323ab0ae-05f0-11e7-8b17-e2c2e8220a03.png)

![image](https://cloud.githubusercontent.com/assets/3648312/23821725/43ba9d08-05f0-11e7-919b-5adceba81712.png)

![image](https://cloud.githubusercontent.com/assets/3648312/23821727/4f8ade90-05f0-11e7-8ea5-0eef2cc8104f.png)

**Comment by carlgogo** [comment]
Hi @astropatel, this is also due to the new Numpy. It's been corrected in the new VIP release. I'm closing this.
