### ISSUE TITLE
Slicing issue in vip.phot.detection?

### ISSUE THREAD

**Issue by joolof** [vortex-exoplanet/VIP#79]
Hi all,

When trying to identify blobs in the 2D image it seems there is a type issue when getting the value at a given pixel coordinates. In vip.phot.detection, line 317 (of version 0.7.1) x and y can be float, and the code tries to get "array[y,x]" which results in an error:

```
/Users/joolof/anaconda/lib/python2.7/site-packages/vip/phot/detection.py in detection(array, psf, bkg_sigma, mode, matched_filter, mask, snr_thresh, plot, debug, full_output, verbose)
    315         snr = snr_ss(array, (x,y), fwhm, False, verbose=False)
    316         snr_list.append(snr)
--> 317         px_list.append(array[y,x])
    318         if snr >= snr_thresh and array[y,x]>0:
    319             if plot:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
If I recall properly, it was working in earlier versions of the code (maybe 0.5 or 0.6, not sure). I have vip version 0.7.1 and numpy version 1.12.1.
Let me know if you need more info or if I missed something.
Cheers, and thanks for the awesome package !
Johan

**Comment by carlgogo** [comment]
Hi @joolof, I fixed this in VIP 0.7.2. Thanks for using VIP and for reporting this bug. This is due to a change done (slicing can be done only with integers) on the last version of Numpy. 
Cheers,
Carlos
