### ISSUE TITLE
Bug (?) in bp_annuli_removal() at line 318: ValueError: too many values to unpack

### ISSUE THREAD

**Issue by owertz** [vortex-exoplanet/VIP#8]
Hi Valentin,

It seems that the function bp_removal_2d() returns more (or less) outputs that output variables:
obj_tmp, bpix_map = bp_removal_2d(...) raises a ValueError: too many values to unpack exception. 

Could you please check that please ?

Thanks in advance,
Olivier

**Comment by VChristiaens** [comment]
Hi Olivier,
thanks for spotting that bug, there is indeed a parameter missing in the case the function is used on a 2d frame instead of a cube. I just made a pull request correcting that minor bug.
Cheers,
Valentin
