### ISSUE TITLE
floats passed as indexes instead of ints

### ISSUE THREAD

**Issue by astropatel** [vortex-exoplanet/VIP#82]
Hey Carlos,

  While running  `register_and_center_via_speckles` in `NIRC2_preprocessing` , I get the error listed in the images. 

Looks like when it hits `vip.var.filters` on line 297, the routine `median_filter` doesn't like it when the `median_size` parameter is a float (e.g. 24.0 instead of 24). I've fixed it temporarily to force it to be an int, but I thought I'd bring this to your attention in case it should be a float/an issue anywhere else in the code.

Cheers,
Rahul

![image](https://user-images.githubusercontent.com/3648312/27970056-3b3b019e-6302-11e7-8d1f-51b06243a42e.png)

**Comment by carlgogo** [comment]
Hi @astropatel, I suspect there might be some int/float issues, I tried to fix most of them but I don't have the time to be more exhaustive. On the other hand, pull requests are always welcomed!!! Btw, thanks @gruane for the PR. 
Cheers,
Carlos
