### ISSUE TITLE
cube_derotate() function recently modified ?

### ISSUE THREAD

**Issue by owertz** [vortex-exoplanet/VIP#9]
Hi @carlgogo , @VChristiaens ,

Could you please tell me if one of you have recently modified the function cube_derotate() (in vip/calib/derotation.py) ? I've tried to run my mcmc stuff but my chiquare() (in vip/negfc/func_merit.py) function doesn't work anymore. It seems the reason is that the cube_derotate() function now returns two outputs instead of one. I'm pretty sure that a couple of days ago it returned only a single array-like object.

Thanks in advance,
Olivier

**Comment by carlgogo** [comment]
Hi @owertz,

It's been always like that. In my first implementation of cube_derotate() with opencv I return the 3d array of rotated frames and the median/mean of the stack.

Cheers,
Carlos

**Comment by owertz** [comment]
Hi Carlos,

Thanks for your answer. I think I’m turning crazy ;-)

Have a good evening,
Olivier


Le 16 oct. 2015 à 18:15, Carlos Gomez <notifications@github.com> a écrit :

> Hi @owertz,
> 
> It's been always like that. In my first implementation of cube_derotate() with opencv I return the 3d array of rotated frames and the median/mean of the stack.
> 
> Cheers,
> Carlos
> 
> —
> Reply to this email directly or view it on GitHub.
> 

********************************************************************
Dr. Olivier WERTZ
Postdoctoral Position - VORTEX Project
E-mail : owertz@ulg.ac.be
Email : wertz@astro.ulg.ac.be
Institut d’Astrophysique et de Géophysique, Fac. Sc., AEOS
AGO: http://www.ago.ulg.ac.be
Université de Liège
Allée du 6 Août, 17, B5c,
B-4000 Sart Tilman, Belgique
********************************************************************
